"""hl_core: what all three Black Mesa campaigns share.

Weapons, items, creatures and people from Half-Life, Opposing Force and Blue
Shift; HEV-style suit armour; health and suit chargers; breakable crates;
procedural Black Mesa regions (offices, labs, maintenance, transit, storage,
the surface, military camps, Xen, Race X hives) for the map generator; the
obstacles it puts on locked doors; and general lore.
"""

from common import direct, gun, throwable, ModBuilder, creature, weapon

B = ModBuilder("hl_core", "hlcore/")
F = B.section("features")

# ---------------------------------------------------------------------------
# The player: HL scale health, suit charge, and suit damage absorption
# ---------------------------------------------------------------------------
F["player"] = {"_patch": True, "props": {"health": 100, "max_health": 100, "suit": 0, "max_suit": 100, "attack": 5}}
F["edible"] = {"_patch": True, "props": {"heal": 10}}

MACROS = {
    "creature_attacks": {"do": [
        {"let": {"hit": "=max(0, self.damage + rand(-scaled(2, 100), scaled(2, 100)) - player.armor - best(player, 'armor'))"}},
        {"let": {"soak": "=min(player.suit, int(hit * 2 / 3))"}},
        {"if": {"local": "hit", "gt": 0},
         "then": [{"add": {"suit": "=-soak", "health": "=-(hit - soak)"}, "on": "player"},
                  {"if": {"local": "soak", "gt": 0},
                   "then": [{"say": "{self.The} {self.attack_text} you for {hit} damage; your suit soaks up {soak}. (Health {player.health}, suit {player.suit})", "style": "warn"}],
                   "else": [{"say": "{self.The} {self.attack_text} you for {hit} damage. (Health {player.health})", "style": "warn"}]}],
         "else": ["{self.The} {self.attack_text} you, but you avoid harm."]},
        {"macro": "check_player_death"}]},
    "hl_suit_charge": {"do": [
        {"let": {"gain": "=min(amount, player.max_suit - player.suit)"}},
        {"add": {"suit": "=gain"}, "on": "player"}]},
}

# ---------------------------------------------------------------------------
# Weapons
# ---------------------------------------------------------------------------
W = {
    # Half-Life
    "crowbar": weapon("crowbar", ["crowbar", "bar"], 10,
        "A red-handled crowbar, heavy and reassuring. Good for crates, headcrabs and stuck hatches.",
        affords=["pry"]),
    "glock": weapon("9mm pistol", ["pistol", "glock", "9mm", "handgun"], 8,
        "A standard-issue 9mm security sidearm. Seventeen rounds and a lot of faith.", ammo=gun("9mm", 17)),
    "python": weapon(".357 Magnum revolver", ["magnum", "revolver", "python", "357"], 25,
        "A six-shot .357 revolver that kicks like a mule and hits harder.", ammo=gun("357", 6)),
    "mp5": weapon("MP5 submachine gun", ["mp5", "smg", "submachine gun", "grenade launcher"], 13,
        "A 9mm submachine gun with an under-barrel grenade launcher.", ammo=gun("9mm", 50)),
    "shotgun": weapon("SPAS-12 shotgun", ["shotgun", "spas", "spas-12"], 22,
        "A pump-action combat shotgun. Fire it twice as fast if you don't mind the recoil.", ammo=gun("buckshot", 8, "shells")),
    "crossbow": weapon("crossbow", ["crossbow", "bow"], 28,
        "A scoped crossbow with explosive-tipped bolts. Works underwater too.", ammo=gun("bolt", 5, "bolts")),
    "rpg": weapon("rocket launcher", ["rpg", "rocket launcher", "launcher"], 45,
        "A laser-guided rocket launcher. Point the dot, and the rocket follows.", ammo=gun("rocket", 1, "rockets")),
    "gauss": weapon("tau cannon", ["tau cannon", "gauss gun", "gauss", "tau"], 32,
        "An experimental prototype that fires charged particle bursts. Charge it too long and it bites you.", ammo=direct("uranium", 2, "uranium")),
    "egon": weapon("gluon gun", ["gluon gun", "egon", "gluon"], 36,
        "A heavy backpack-mounted gluon beam projector. It eats depleted uranium like nobody's business.", ammo=direct("uranium", 1, "uranium")),
    "hivehand": weapon("hivehand", ["hivehand", "hornet gun", "hive"], 10,
        "A living alien weapon that grows homing hornets. It squirms when you hold it.",
        tags=["alien"]),
    "snark_nest": weapon("snark nest", ["snarks", "snark nest", "nest"], 9,
        "A twitching pod of snarks. Throw one, and it hunts whatever is nearest. Usually.", ammo=throwable("snarks", 5, "The last snark scuttles off; the nest is empty.")),
    "grenade": weapon("hand grenade", ["grenade", "grenades", "frag"], 30,
        "A fragmentation grenade. Pull the pin and count.", ammo=throwable("grenades", 1, "The grenade goes off with a flat crack.")),
    "satchel": weapon("satchel charge", ["satchel", "satchel charge", "charge"], 40,
        "A remote-detonated satchel charge.", affords=["explosive"], ammo=throwable("charges", 1, "The satchel charge goes up with a roar.")),
    "tripmine": weapon("laser tripmine", ["tripmine", "laser tripmine", "mine"], 30,
        "A laser-triggered mine for walls.", affords=["explosive"], ammo=throwable("mines", 1, "The tripmine detonates.")),
    # Opposing Force
    "pipe_wrench": weapon("pipe wrench", ["pipe wrench", "wrench"], 12,
        "A heavy pipe wrench. Slower than a crowbar, and it hits harder.", affords=["pry"]),
    "combat_knife": weapon("combat knife", ["knife", "combat knife"], 9,
        "A standard Marine combat knife. Quick and quiet."),
    "desert_eagle": weapon("Desert Eagle", ["desert eagle", "deagle", "eagle", ".50"], 20,
        "A .50 calibre handgun with a laser sight.", ammo=gun("357", 7)),
    "m249": weapon("M249 squad automatic weapon", ["m249", "saw", "machine gun", "squad automatic weapon"], 18,
        "A belt-fed light machine gun. Fires until the belt runs out or you fall over.", ammo=gun("556", 50)),
    "sniper_rifle": weapon("M40A1 sniper rifle", ["sniper rifle", "sniper", "m40a1", "rifle"], 35,
        "A bolt-action sniper rifle with a long-range scope.", ammo=gun("762", 5)),
    "shock_roach": weapon("shock roach", ["shock roach", "roach"], 14,
        "A Race X creature that spits bolts of electricity and recharges itself. It is, apparently, happy to see you.",
        tags=["alien"]),
    "spore_launcher": weapon("spore launcher", ["spore launcher", "spore", "launcher"], 26,
        "A living alien launcher that hurls explosive spore pods. It chirps when fed.",
        tags=["alien"], ammo=gun("spore", 5, "spores")),
    "displacer": weapon("displacer cannon", ["displacer", "displacer cannon", "cannon"], 48,
        "An experimental portal weapon. It sends whatever it hits somewhere else, or sends you somewhere else.",
        affords=["teleport"], ammo=direct("uranium", 20, "uranium")),
    "grapple": weapon("barnacle grapple", ["grapple", "barnacle", "barnacle grapple"], 6,
        "A captured barnacle that shoots its tongue at anything organic and hauls you after it.",
        tags=["alien"], affords=["grapple"]),
    "penguin": weapon("penguin", ["penguin"], 9,
        "An explosive penguin. A multiplayer joke from the Opposing Force era that nobody has ever explained.",
        tags=["alien"], ammo=throwable("penguins", 3, "The last penguin waddles off to meet its destiny.")),
}
F.update(W)


# ---------------------------------------------------------------------------
# Ammunition: supplies (core's supply trait) for the consumer weapons above.
# Use one by itself to load whatever you carry that takes it, or 'reload <gun>'.
# ---------------------------------------------------------------------------
def ammo(name, aliases, kind, amount, desc, habitat=("blackmesa", "military", "surface"), weight=2):
    return {"extends": ["supply"], "name": name, "aliases": aliases + ["ammo", "ammunition"],
            "tags": ["scatter", "hl_pickup", "hl_ammo"], "habitat": list(habitat), "weight": weight,
            "props": {"ammo": amount, "ammo_type": kind}, "description": desc}


AMMO = {
    "ammo_9mm": ammo("box of 9mm rounds", ["9mm", "9mm rounds", "rounds", "box", "clip"], "9mm", 34,
        "Two magazines' worth of 9mm. Fits the pistol and the MP5.", weight=4),
    "ammo_357": ammo("pack of .357 rounds", [".357", "357", ".357 rounds", "magnum rounds"], "357", 12,
        "Six-shooter rounds, also good for a Desert Eagle."),
    "ammo_buckshot": ammo("box of buckshot", ["buckshot", "shells", "shotgun shells"], "buckshot", 12,
        "Twelve-gauge shells, red and brass.", weight=3),
    "ammo_bolts": ammo("bundle of crossbow bolts", ["bolts", "crossbow bolts", "bundle"], "bolt", 5,
        "Explosive-tipped bolts for the crossbow.", weight=1),
    "ammo_rocket": ammo("rocket", ["rocket", "rockets", "rpg round"], "rocket", 1,
        "A single laser-guided rocket.", habitat=("military", "surface"), weight=1),
    "ammo_uranium": ammo("depleted uranium cell", ["uranium", "uranium cell", "cell", "du cell"], "uranium", 20,
        "A glowing canister of depleted uranium. The tau cannon, the gluon gun and the displacer all drink it.",
        habitat=("blackmesa", "lab"), weight=1),
    "ammo_556": ammo("5.56mm ammunition belt", ["5.56", "556", "belt", "ammunition belt"], "556", 50,
        "A belt of 5.56mm for the M249.", habitat=("military", "surface"), weight=1),
    "ammo_762": ammo("box of 7.62mm rounds", ["7.62", "762", "sniper rounds"], "762", 5,
        "Match-grade rounds for a sniper rifle.", habitat=("military", "surface"), weight=1),
    "ammo_spore": ammo("spore pod", ["spore pod", "pod", "spores"], "spore", 2,
        "A Race X spore pod, warm and faintly twitching. The spore launcher eats them.", habitat=("racex", "alien"), weight=1),
}
AMMO_COMMON = ["ammo_9mm", "ammo_9mm", "ammo_buckshot", "ammo_357"]
AMMO_RARE = ["ammo_bolts", "ammo_rocket", "ammo_uranium", "ammo_556", "ammo_762"]
F.update(AMMO)

# ---------------------------------------------------------------------------
# Items and pickups
# ---------------------------------------------------------------------------
F.update({
    "hev_suit": {"extends": ["portable"], "name": "HEV suit", "aliases": ["hev", "suit", "hazard suit", "mark iv"],
        "story_keep": True, "tags": ["armour"], "affords": ["hazard"],
        "props": {"armor": 1},
        "description": "The Mark IV Hazardous Environment suit: radiation shielding, a power-armour layer charged by batteries, an injector system and a voice that announces every misfortune in a soothing female tone.",
        "actions": {"take": [{"if": {"held": "self"}, "do": ["You're already wearing it."]},
            {"do": [{"move": "self", "to": "player"}, {"set": {"max_suit": 100}, "on": "player"}, {"flag": "hl_hev"},
                    {"say": "You climb into the HEV suit. A calm synthetic voice runs through its start-up checks: power armour, atmospheric contaminant sensors, vital sign monitoring, munition level monitoring, communications. All systems nominal. Have a very safe day.", "style": "story"}]}]}},
    "pcv": {"extends": ["portable"], "name": "Powered Combat Vest", "aliases": ["pcv", "vest", "combat vest"],
        "story_keep": True, "tags": ["armour"], "props": {"armor": 1},
        "description": "The HECU's Powered Combat Vest: kevlar plates with a battery-charged armour layer.",
        "actions": {"take": [{"if": {"held": "self"}, "do": ["You're already wearing it."]},
            {"do": [{"move": "self", "to": "player"}, "You strap on the PCV. Its charge indicator glows."]}]}},
    "security_vest": {"extends": ["portable"], "name": "security vest", "aliases": ["vest", "kevlar", "body armour"],
        "story_keep": True, "tags": ["armour"], "props": {"armor": 1},
        "description": "A Black Mesa security kevlar vest. Not an HEV suit, but it stops a 9mm round."},
    "security_helmet": {"extends": ["portable"], "name": "security helmet", "aliases": ["helmet"],
        "story_keep": True, "tags": ["armour"], "props": {"armor": 1},
        "description": "A Black Mesa security helmet with a dark visor."},
    "medkit": {"extends": ["edible"], "name": "first aid kit", "aliases": ["medkit", "first aid kit", "kit", "health kit"],
        "tags": ["scatter", "hl_pickup"], "habitat": ["blackmesa", "military", "surface"], "weight": 3, "affords": ["medicine"],
        "props": {"heal": 15, "taste": "You tear open the kit and patch yourself up."},
        "description": "A white first aid kit with a red cross. Bandages, a stimulant shot, the usual."},
    "battery": {"extends": ["portable"], "name": "suit battery", "aliases": ["battery", "suit battery", "hev battery"],
        "tags": ["scatter", "hl_pickup"], "habitat": ["blackmesa", "military", "surface"], "weight": 3,
        "affords": ["power"],
        "description": "A Black Mesa suit battery. Snap it into a suit's charging port.",
        "actions": {"use": [{"if": {"second": None}, "do": [{"macro": "hl_suit_charge", "with": {"amount": 15}},
            "You snap the battery into your suit. (Suit {player.suit})", {"destroy": "self"}]}],
                    "eat": ["You'd rather not."]}},
    "ammo_box": {"extends": ["scenery", "container"], "name": "ammunition cache", "aliases": ["cache", "ammunition cache", "ammo cache"],
        "tags": ["scatter", "hl_pickup"], "habitat": ["blackmesa", "military", "surface"], "weight": 3,
        "appearance": "A stash of ammunition has been left here.",
        "description": "Somebody's ammunition, stacked where they dropped it. In this place, you can never have enough.",
        "contents_text": "In the cache: {contents}.", "empty_text": "The cache has been picked clean.",
        "features": [{"pick": AMMO_COMMON}, {"chance": 0.4, "pick": AMMO_COMMON + AMMO_RARE}]},
    "long_jump": {"extends": ["portable"], "name": "long jump module", "aliases": ["long jump", "module", "ljm", "jump module"],
        "story_keep": True, "affords": ["jump"],
        "description": "An experimental HEV attachment that fires a short thrust for enormous leaps. Crouch, then jump.",
        "actions": {"take": [{"if": {"held": "self"}, "do": ["It's already fitted."]},
            {"do": [{"move": "self", "to": "player"}, {"say": "You clip the long jump module to the back of your suit. It hums.", "style": "story"}]}]}},
    "night_vision": {"extends": ["portable"], "name": "night vision goggles", "aliases": ["goggles", "night vision", "nvg"],
        "story_keep": True, "affords": ["light"],
        "description": "HECU night vision goggles, which turn the dark a ghostly green."},
    "bm_keycard": {"extends": ["portable"], "name": "#bm_card_colour# security keycard", "aliases": ["keycard", "card", "security card"],
        "affords": ["access"], "home": ["blackmesa", "office"],
        "description": "A Black Mesa keycard on a clip. A security clearance stripe runs along the edge."},
    "blowtorch": {"extends": ["portable"], "name": "engineer's blowtorch", "aliases": ["blowtorch", "torch", "cutting torch"],
        "affords": ["cut"], "story_keep": True,
        "description": "A HECU combat engineer's cutting torch. It goes through welded doors like they owe it money."},
    "radio": {"extends": ["portable"], "name": "field radio", "aliases": ["radio", "handset"],
        "affords": ["radio"], "description": "A military field radio, tuned to a HECU frequency."},
})

# ---------------------------------------------------------------------------
# Scenery and interactive fixtures
# ---------------------------------------------------------------------------
F.update({
    "health_charger": {"extends": ["scenery"], "name": "health charger", "aliases": ["health charger", "health station", "medical station", "charger"],
        "props": {"charge": 50},
        "appearance": [{"if": {"prop": "charge", "gt": 0}, "text": "A wall-mounted health charger glows a steady green."},
                       {"text": "A health charger on the wall has gone dark, its reservoir empty."}],
        "description": "A Black Mesa medical station. Press your palm to it and it injects morphine and a coagulant cocktail.",
        "actions": {"use": [
            {"if": {"prop": "charge", "lte": 0}, "do": ["The charger buzzes. Empty."]},
            {"if": "player.health >= player.max_health", "do": ["You're in no need of it."]},
            {"do": [{"let": {"gain": "=min(self.charge, player.max_health - player.health)"}},
                    {"add": {"health": "=gain"}, "on": "player"}, {"add": {"charge": "=-gain"}},
                    "The charger hums and stings. (Health {player.health})"]}]}},
    "suit_charger": {"extends": ["scenery"], "name": "HEV charger", "aliases": ["hev charger", "suit charger", "charger", "power station"],
        "props": {"charge": 75},
        "appearance": [{"if": {"prop": "charge", "gt": 0}, "text": "An HEV charging station hums on the wall, its readout glowing orange."},
                       {"text": "An HEV charging station on the wall is drained and silent."}],
        "description": "A wall unit that recharges a suit's power armour.",
        "actions": {"use": [
            {"if": {"prop": "charge", "lte": 0}, "do": ["The charger whines. Drained."]},
            {"if": "player.suit >= player.max_suit", "do": ["Your suit is already fully charged."]},
            {"do": [{"let": {"gain": "=min(self.charge, player.max_suit - player.suit)"}},
                    {"add": {"suit": "=gain"}, "on": "player"}, {"add": {"charge": "=-gain"}},
                    "Power crackles into your suit. (Suit {player.suit})"]}]}},
    "supply_crate": {"extends": ["scenery", "container"], "name": "#crate_kind#", "aliases": ["crate", "box", "supply crate"],
        "tags": ["scatter", "crate"], "habitat": ["blackmesa", "military", "storage", "surface"], "weight": 4,
        "props": {"open": False},
        "contents_visible": {"prop": "open"},
        "appearance": [{"if": {"prop": "open"}, "text": "A smashed crate lies in pieces."}, {"text": "A wooden supply crate is stacked here."}],
        "description": "A wooden crate stencilled with Black Mesa inventory codes.",
        "contents_text": "Among the splinters: {contents}.",
        "features": [{"chance": 0.6, "pick": ["medkit", "battery", "ammo_9mm", "ammo_buckshot", "ammo_357"]}, {"chance": 0.15, "pick": ["grenade", "glock", "satchel"]}],
        "actions": {
            "open": [{"if": {"prop": "open"}, "do": ["It's already been smashed open."]},
                     {"if": {"has": {"affords": ["pry"]}}, "do": [{"set": {"open": True}}, "You lever the lid off. Inside: {self.contents}."]},
                     {"do": [{"set": {"open": True}}, "It's nailed shut, so you stamp on the lid until the planks give. Inside: {self.contents}."]}],
            "attack": [{"if": {"prop": "open"}, "do": ["There's nothing left to break."]},
                       {"do": [{"set": {"open": True}}, "The crate splinters apart. Inside: {self.contents}."]}],
            "use_with": [{"if": {"is": {"affords": ["pry"]}, "of": "target"}, "do": [{"set": {"open": True}}, "You crack the crate open with {target}. Inside: {self.contents}."]}]}},
    "vending_machine": {"extends": ["scenery"], "name": "soda machine", "aliases": ["vending machine", "soda machine", "machine"],
        "appearance": "A soda machine hums against the wall.",
        "description": "It sells cans of something brightly coloured. The fizzy kind of pick-me-up.",
        "actions": {"use": [{"do": [{"spawn": "soda_can", "in": "room"}, "A can thunks into the tray."]}],
                    "attack": [{"do": [{"spawn": "soda_can", "in": "room"}, "You give it a whack. A can rattles out."]}],
                    "push": ["It rocks, but holds its ground."]}},
    "soda_can": {"extends": ["drinkable"], "name": "can of soda", "aliases": ["can", "soda", "pop"],
        "props": {"taste": "Sweet, flat, and somehow exactly what you needed.", "heal": 1},
        "description": "A cold can of soda."},
    "bm_terminal": {"extends": ["scenery", "readable"], "name": "computer terminal", "aliases": ["terminal", "computer", "screen", "monitor"],
        "tags": ["lore_carrier"], "habitat": ["blackmesa", "office", "lab"],
        "appearance": "A beige computer terminal flickers on a desk.",
        "description": "A Black Mesa workstation, its green text scrolling.",
        "props": {"text": "#bm_terminal_text#"}},
    "bm_memo": {"extends": ["portable", "readable"], "name": "#memo_kind#", "aliases": ["memo", "note", "paper", "printout", "clipboard"],
        "tags": ["lore_carrier"], "habitat": ["blackmesa", "office", "lab", "storage"],
        "description": "Black Mesa letterhead, coffee-stained."},
    "hecu_logbook": {"extends": ["portable", "readable"], "name": "field logbook", "aliases": ["logbook", "log", "book", "notes"],
        "tags": ["lore_carrier"], "habitat": ["military", "surface"],
        "description": "A HECU field logbook in a waterproof cover."},
    "xen_glyph": {"extends": ["scenery", "readable"], "name": "alien glyph", "aliases": ["glyph", "markings", "symbols"],
        "tags": ["lore_carrier"], "habitat": ["xen", "alien"],
        "appearance": "Strange glowing glyphs are etched into the rock.",
        "description": "They pulse slowly. Looking at them for too long makes your teeth ache."},
    "dead_scientist": {"extends": ["scenery"], "name": "dead scientist", "aliases": ["body", "corpse", "scientist", "dead scientist"],
        "tags": ["scatter"], "habitat": ["blackmesa", "lab", "office"], "weight": 2,
        "appearance": "A scientist lies dead here, lab coat stained dark.",
        "description": "Whatever happened, it happened fast.",
        "features": [{"chance": 0.3, "pick": ["medkit", "bm_keycard", "bm_memo"], "hidden": True}],
        "actions": {"take": ["You leave the dead in peace."]}},
    "dead_guard": {"extends": ["scenery"], "name": "dead security guard", "aliases": ["body", "corpse", "guard", "dead guard"],
        "tags": ["scatter"], "habitat": ["blackmesa", "office", "transit"], "weight": 1,
        "appearance": "A security guard lies slumped against the wall, his helmet askew.",
        "description": "His holster is open.",
        "features": [{"chance": 0.5, "pick": ["glock", "ammo_9mm", "battery"], "hidden": True}],
        "actions": {"take": ["You leave the dead in peace."]}},
    "dead_marine": {"extends": ["scenery"], "name": "dead marine", "aliases": ["body", "corpse", "marine", "soldier"],
        "tags": ["scatter"], "habitat": ["military", "surface"], "weight": 2,
        "appearance": "A HECU marine lies face-down here in his gas mask.",
        "description": "His webbing is still full of gear.",
        "features": [{"chance": 0.6, "pick": ["mp5", "ammo_9mm", "ammo_556", "grenade", "medkit", "hecu_logbook"], "hidden": True}],
        "actions": {"take": ["You leave the dead in peace."]}},
    "cockroach": {"extends": ["scenery"], "name": "cockroach", "aliases": ["roach", "cockroach", "bug"],
        "tags": ["scatter"], "habitat": ["maintenance", "storage", "office"],
        "appearance": "A cockroach scuttles along the skirting board.",
        "description": "Black Mesa's longest-serving employee.",
        "actions": {"attack": [{"do": ["You step on it with a satisfying crunch.", {"destroy": "self"}]}],
                    "take": ["It skitters away."]}},
    "xen_light": {"extends": ["scenery"], "name": "xen light stalk", "aliases": ["stalk", "light stalk", "plant", "light"],
        "tags": ["scatter"], "habitat": ["xen", "rift"],
        "appearance": "A glowing light-stalk sways here, retracting shyly when you come near.",
        "description": "A bioluminescent stalk with a bulb that pulls back into the ground at the slightest disturbance."},
    "healing_pool": {"extends": ["scenery"], "name": "healing pool", "aliases": ["pool", "healing pool", "water"],
        "appearance": "A shallow pool of glowing water ripples here.",
        "description": "The water is warm and faintly luminous. Wounds close where it touches them.",
        "actions": {"use": [{"do": [{"set": {"health": "=player.max_health"}, "on": "player"}, "You wade into the glowing pool. Your wounds knit closed. (Health {player.health})"]}],
                    "drink": [{"do": [{"set": {"health": "=player.max_health"}, "on": "player"}, "You drink the glowing water. Strength floods back. (Health {player.health})"]}]}},
    "barnacle": {"extends": ["hostile"], "name": "barnacle", "aliases": ["barnacle", "tongue", "ceiling thing"],
        "tags": ["encounter", "hl_creature"], "habitat": ["maintenance", "storage", "xen", "lab", "office"], "weight": 2,
        "props": {"health": 25, "max_health": 25, "damage": 5, "armor": 0, "attack_text": "snags you with its tongue and reels",
                  "death_text": "The barnacle shudders and lets go, spitting out a ribcage and something shiny."},
        "appearance": "A barnacle clings to the ceiling here, its long sticky tongue dangling to the floor.",
        "description": "A ceiling-dwelling Xen predator. It hauls up whatever touches its tongue and chews.",
        "on_death": [{"spawn": {"pick": ["battery", "medkit", "ammo_9mm"]}, "in": "room"}]},
})

C = {
    # Half-Life / shared Xen fauna
    "headcrab": creature("headcrab", ["headcrab", "crab", "parasite"], 12, 6, "leaps at your face and bites",
        "A fleshy, beaked Xen parasite that latches onto heads. You know what happens next.",
        "A headcrab scuttles across the floor, then rears up, ready to leap.",
        habitat=["blackmesa", "lab", "office", "maintenance", "xen", "storage", "transit", "rift"], weight=4),
    "baby_headcrab": creature("baby headcrab", ["baby headcrab", "baby crab"], 4, 2, "nips at your ankles",
        "A tiny headcrab, fresh from the Gonarch.", "Baby headcrabs swarm over the ground.",
        habitat=["xen"], weight=1),
    "zombie": creature("zombie", ["zombie", "zombie scientist", "headcrab zombie"], 35, 12, "rakes you with its claws",
        "A scientist with a headcrab clamped over his head, his ribcage split open into a second mouth. He groans for help.",
        "A zombie in a torn lab coat staggers toward you, moaning.",
        habitat=["blackmesa", "lab", "office", "maintenance"], weight=3,
        death="The zombie collapses. The headcrab twitches once and is still."),
    "houndeye": creature("houndeye", ["houndeye", "hound"], 20, 9, "lets loose a shrieking sonic blast at",
        "A three-legged Xen pack animal with one great eye and a sonic attack. They hunt in packs and chirp to each other.",
        "A houndeye blinks at you with its single huge eye, warbling a warning.",
        habitat=["blackmesa", "maintenance", "surface", "xen", "storage", "lab", "rift"], weight=3),
    "bullsquid": creature("bullsquid", ["bullsquid", "squid"], 40, 11, "spits burning acid at",
        "A squat, tentacle-mouthed predator that lurks near water and spits acid. It hates headcrabs almost as much as it hates you.",
        "A bullsquid lurches toward you, mouth-tentacles writhing.",
        habitat=["maintenance", "surface", "xen", "water", "sewer"], weight=2),
    "vortigaunt": creature("vortigaunt", ["vortigaunt", "alien slave", "slave", "vort"], 30, 13, "hurls a crackling green bolt of lightning at",
        "A hunched, one-eyed alien with a collar of shackles, channelling green electricity through its claws. It murmurs in a language you don't know.",
        "A vortigaunt warps in with a crackle of green light, arms already charging.",
        habitat=["blackmesa", "lab", "office", "surface", "xen", "maintenance", "rift"], weight=2),
    "alien_grunt": creature("alien grunt", ["alien grunt", "agrunt", "grunt"], 60, 13, "fires a stream of homing hornets at",
        "A hulking, armoured Xen soldier with a living hivehand bolted to its arm.",
        "An alien grunt lumbers forward, its hivehand buzzing.",
        habitat=["xen", "surface", "lab", "alien"], weight=2, min_stage=1, armor=1,
        extra={"on_death": [{"spawn": {"pick": ["hivehand", "ammo_uranium"], "chance": 0.2}, "in": "room"}]}),
    "controller": creature("alien controller", ["controller", "alien controller"], 40, 14, "hurls glowing energy balls at",
        "A floating, foetal-looking alien with a huge head, psychic and hateful.",
        "An alien controller drifts overhead, its swollen head glowing.",
        habitat=["xen", "alien"], weight=1, min_stage=1),
    "ichthyosaur": creature("ichthyosaur", ["ichthyosaur", "ichy", "fish", "sea creature"], 60, 18, "lunges out of the water and bites",
        "A huge eel-like aquatic predator with too many teeth and a fondness for anything that swims.",
        "Something huge circles in the water. An ichthyosaur breaks the surface, jaws gaping.",
        habitat=["water"], weight=1),
    "leech": creature("leech", ["leech", "leeches"], 3, 2, "fastens onto your leg and sucks",
        "A small Xen leech that lives in dark water.", "Leeches flicker in the dark water.",
        habitat=["water", "sewer"], weight=1),
    "snark": creature("snark", ["snark", "snarks"], 6, 3, "chitters and bites",
        "A small, red, beetle-like Xen creature that explodes when it has done enough biting.",
        "A snark scuttles toward you, chittering.", habitat=["xen", "lab"], weight=1),
    "gargantua": creature("gargantua", ["gargantua", "garg", "giant"], 300, 28, "sweeps a gout of flame over",
        "A towering, armoured Xen colossus that breathes fire from its forearms and stomps anything smaller than a tank.",
        "A gargantua towers here, its eye glowing, flame-throwers flaring on its arms.",
        encounter=False, armor=3, death="The gargantua staggers, its armour cracking with light, and explodes in a shower of gore."),
    "gonarch": creature("Gonarch", ["gonarch", "big mama", "mother"], 150, 16, "slams a bony leg into",
        "The adult form of the headcrab: a huge armoured sac on four long legs, spawning babies as it hunts.",
        "The Gonarch rears up on its four legs, its swollen sac pulsing.",
        encounter=False, armor=2, death="The Gonarch shrieks, bursts, and falls in on itself."),
    "nihilanth": creature("Nihilanth", ["nihilanth", "giant", "the nihilanth", "creature"], 220, 15, "hurls a storm of electric spheres at",
        "A colossal floating foetus with a vast cranium and withered arms, crowned by healing crystals. Its voice fills your skull.",
        "The Nihilanth hangs in the air at the heart of the chamber, enormous, its voice echoing in your head.",
        encounter=False, armor=2, death="The Nihilanth's skull splits open with light. It screams across every dimension at once."),
    "tentacle": {"extends": ["scenery"], "name": "tentacles", "aliases": ["tentacle", "tentacles", "beak", "monster"],
        "tags": ["hl_creature"], "article": "the",
        "appearance": [{"if": {"flag": "hl_tentacles_dead"}, "text": "Charred stumps of the tentacles hang slack in the silo."},
                       {"text": "Three gigantic tentacles rise from the silo floor, beaked tips probing for sound."}],
        "description": "They are blind, and hunt by sound. Their beaks punch through steel.",
        "actions": {"attack": [{"if": {"flag": "hl_tentacles_dead"}, "do": ["They're already burned to a crisp."]},
                               {"do": ["You might as well shoot a building. The tentacles shrug it off and slam toward the sound."]}]}},
    "hecu_marine": creature("HECU marine", ["marine", "soldier", "grunt", "hecu", "hecu marine"], 40, 11, "opens fire on",
        "A Hazardous Environment Combat Unit marine in a gas mask and fatigues, sent to clean up the incident. Including witnesses.",
        "A HECU marine shouts to his squad and opens fire.",
        habitat=["military", "surface", "office", "storage", "blackmesa"], weight=3, min_stage=1, armor=1, tags=["hecu"],
        extra={"on_death": [{"spawn": {"pick": ["mp5", "ammo_9mm", "ammo_9mm", "ammo_buckshot", "grenade", "shotgun", "medkit"], "chance": 0.5}, "in": "room"}]}),
    "sentry_gun": creature("sentry gun", ["sentry", "sentry gun", "turret", "gun"], 30, 9, "sprays bullets at",
        "An automated tripod gun with a motion sensor and a short temper.",
        "A sentry gun swivels toward you, beeping.", habitat=["military", "office", "blackmesa"], weight=1, min_stage=1, armor=1,
        death="The sentry gun sparks and topples over."),
    "apache": creature("Apache helicopter", ["apache", "helicopter", "chopper", "gunship"], 150, 22, "strafes",
        "An AH-64 Apache helicopter gunship, rotor thumping, nose gun tracking.",
        "An Apache helicopter thunders overhead, nose gun swinging toward you.",
        encounter=False, armor=3, death="The Apache shudders, trails black smoke and plunges out of sight into the canyon."),
    "female_assassin": creature("black ops assassin", ["assassin", "black ops", "ninja", "female assassin"], 40, 13, "flips past you and fires a silenced pistol at",
        "A Black Ops agent in a black catsuit and night-vision goggles, silent and acrobatic.",
        "A black-clad assassin drops from the shadows, silenced pistol raised.",
        habitat=["surface", "military", "blackmesa"], weight=1, min_stage=2, armor=1, tags=["black_ops"]),
    # Opposing Force
    "male_assassin": creature("black ops operative", ["operative", "black ops", "male assassin", "assassin"], 45, 13, "fires a burst at",
        "A Black Ops operative in a balaclava and night-vision goggles, armed with an MP5 or a sniper rifle.",
        "A Black Ops operative signals to his team and opens fire.",
        habitat=["surface", "military", "blackmesa"], weight=1, min_stage=1, armor=1, tags=["black_ops"]),
    "zombie_guard": creature("zombie security guard", ["zombie guard", "zombie", "guard zombie"], 40, 12, "claws at",
        "A security guard taken by a headcrab, kevlar vest and all.", "A zombie in a security uniform shambles toward you.",
        habitat=["blackmesa", "office", "maintenance"], weight=1),
    "zombie_soldier": creature("zombie soldier", ["zombie soldier", "zombie", "zombie marine"], 45, 13, "lashes out at",
        "A HECU marine taken by a headcrab, gas mask still on under it.", "A zombified marine lurches toward you.",
        habitat=["military", "maintenance", "blackmesa"], weight=1, min_stage=1),
    "gonome": creature("gonome", ["gonome", "zombie"], 60, 15, "hurls a gob of bile at",
        "What a headcrab zombie becomes when left long enough: the headcrab fused into the host, a gaping chest maw full of teeth.",
        "A gonome lurches out of the dark, its chest-maw gaping.", habitat=["blackmesa", "maintenance", "lab"], weight=1, min_stage=1),
    "pit_drone": creature("pit drone", ["pit drone", "drone"], 35, 11, "fires a volley of spikes at",
        "A Race X creature with a head full of spikes it can shoot.", "A pit drone skitters toward you, head-spikes quivering.",
        habitat=["racex", "alien", "blackmesa", "maintenance"], weight=2, min_stage=1, tags=["racex"]),
    "shock_trooper": creature("shock trooper", ["shock trooper", "trooper", "race x soldier"], 55, 14, "fires its shock roach at",
        "A tall Race X soldier carrying a living shock roach as a weapon. Its single eye glows.",
        "A shock trooper warps in with a crackle, shock roach raised.", habitat=["racex", "alien", "surface", "blackmesa"], weight=2,
        min_stage=1, armor=1, tags=["racex"],
        extra={"on_death": [{"spawn": {"id": "shock_roach", "chance": 0.5}, "in": "room"}]}),
    "voltigore": creature("voltigore", ["voltigore"], 120, 22, "hurls a ball of purple lightning at",
        "A huge Race X beast with a mouth full of electricity. When it dies, it explodes.", "A voltigore crashes through, purple lightning crackling between its jaws.",
        habitat=["racex", "alien"], weight=1, min_stage=2, armor=2, tags=["racex"],
        death="The voltigore crackles, swells and explodes in a burst of purple light."),
    "baby_voltigore": creature("baby voltigore", ["baby voltigore", "voltigore"], 25, 8, "snaps at",
        "A young voltigore, already sparking.", "A baby voltigore scrabbles toward you.", habitat=["racex", "alien"], weight=1, tags=["racex"]),
    "pit_worm": creature("pit worm", ["pit worm", "worm"], 150, 18, "lashes out with its laser-eye at",
        "A vast Race X worm that lives in deep water, with an eye that projects a cutting beam.",
        "The pit worm rises from the waste water, its eye blazing.", encounter=False, armor=3,
        death="The pit worm sinks screaming into the sludge."),
    "gene_worm": creature("Gene Worm", ["gene worm", "worm", "gene"], 260, 20, "sprays a torrent of corrosive toxin over",
        "A colossal Race X bio-engineer that converts whatever world it reaches into a habitat for its kind. It came through a portal, and it has eyes the size of cars.",
        "The Gene Worm fills the portal, vast and slick, its armoured eyes swivelling.", encounter=False, armor=2,
        death="The Gene Worm convulses, collapses into the portal and is torn apart as the rift closes."),
}
F.update(C)

# ---------------------------------------------------------------------------
# People
# ---------------------------------------------------------------------------
SCIENTIST_PROFILE = {
    "personality": ["nervous"], "motives": ["knowledge", "survive"],
    "motive_text": "get out of here alive, and maybe write a paper about it",
    "goals": ["reach the surface", "find out what went wrong with the test", "save the data"],
    "backstory": "\"I work in #bm_department#. Worked. Whatever.\"",
    "roles": ["giver", "informant", "holder", "ally", "victim"], "knows": ["blackmesa", "science", "xen", "lambda"],
    "wants": ["medicine"], "greet": ["The scientist peers at you over his glasses. \"Oh! I thought you were... never mind.\""],
    "epilogue": "{speaker.The} survives, somehow, and never takes another job underground.",
}
GUARD_PROFILE = {
    "personality": ["cheerful", "weary"], "motives": ["duty", "survive", "protect"],
    "motive_text": "get everybody out who can still walk",
    "goals": ["get the scientists to the surface", "find a working radio", "have a beer once this is over"],
    "backstory": "\"Security. I check badges, unlock doors and get yelled at by scientists. Today I'm getting shot at too.\"",
    "roles": ["giver", "informant", "holder", "ally", "victim", "authority"], "knows": ["blackmesa", "security", "rumour"],
    "wants": ["weapon", "medicine", "power"],
    "epilogue": "{speaker.The} makes it out, and swears the first round's on him.",
}
F.update({
    "scientist": {"extends": ["person"], "name": "Dr. #bm_surname#", "proper": True,
        "aliases": ["scientist", "doctor", "dr"], "tags": ["scientist", "bm_staff"],
        "appearance": "{self.Name}, a Black Mesa scientist in a white lab coat, is here.",
        "description": "Lab coat, ID badge, glasses, and the expression of someone whose theories are being tested in the worst possible way.",
        "profile": SCIENTIST_PROFILE,
        "actions": {"talk": [{"do": ["\"#scientist_chatter#\""]}]}},
    "security_guard": {"extends": ["person"], "name": "Officer #bm_surname#", "proper": True,
        "aliases": ["guard", "security guard", "officer", "barney"], "tags": ["security", "bm_staff"],
        "appearance": "{self.Name}, a Black Mesa security guard, stands here in his blue shirt and kevlar vest.",
        "description": "Blue shirt, kevlar vest, helmet pushed back, 9mm on his hip. Every guard here looks a bit alike.",
        "profile": GUARD_PROFILE,
        "actions": {"talk": [{"do": ["\"#guard_chatter#\""]}]}},
    "gman": {"extends": ["person"], "name": "G-Man", "proper": True,
        "aliases": ["g-man", "gman", "man in the suit", "man", "suit", "briefcase"], "tags": ["gman"],
        "appearance": "A thin man in a blue suit, briefcase in hand, watches you from a little too far away.",
        "description": "Pale, gaunt, immaculate. He speaks in strange pauses and stresses the wrong syllables. Nobody on the staff list matches him.",
        "profile": {"personality": ["cold", "cunning"], "motives": ["employer", "order", "control"],
            "motive_text": "see that certain events unfold... according to plan",
            "goals": ["recruit a promising individual", "keep his employers satisfied"],
            "backstory": "He smiles thinly. \"Who I am is... not important. What matters is what you do... next.\"",
            "roles": ["informant", "giver", "antagonist"], "knows": ["xen", "lambda", "gman"],
            "greet": ["The man in the suit straightens his tie and regards you with interest."],
            "epilogue": ""},
        "actions": {"talk": [{"do": ["He adjusts his tie, looks at you a moment too long, and says nothing at all."]}],
                    "attack": ["Your aim slides off him as though he were somewhere else entirely."]}},
    "hecu_ally": {"extends": ["person"], "name": "#hecu_rank# #hecu_surname#", "proper": True,
        "aliases": ["marine", "soldier", "grunt", "corporal", "private", "sergeant"], "tags": ["hecu", "ally"],
        "appearance": "{self.Name}, a HECU marine of your unit, covers the corners with his rifle.",
        "description": "Gas mask, fatigues, MP5. He nods at you: one of yours.",
        "profile": {"personality": ["gruff"], "motives": ["duty", "survive", "orders"],
            "motive_text": "complete the mission and get back to the extraction point",
            "goals": ["get out on the last Osprey", "find the rest of the squad"],
            "backstory": "\"Same as you, Corporal. Dropped into this mess and told to clean it up.\"",
            "roles": ["giver", "informant", "holder", "ally", "victim"], "knows": ["hecu", "military"],
            "wants": ["weapon", "medicine"],
            "epilogue": "{speaker.The} makes it home. He never talks about Black Mesa, not once."},
        "actions": {"talk": [{"do": ["\"#hecu_chatter#\""]}]}},
    "hecu_medic": {"extends": ["hecu_ally"], "name": "Medic #hecu_surname#", "proper": True,
        "aliases": ["medic", "corpsman", "doc"], "tags": ["hecu", "ally", "medic"],
        "appearance": "{self.Name}, a HECU field medic with a white helmet cross, checks his kit here.",
        "description": "A combat medic, satchel full of morphine and patience.",
        "actions": {"talk": [{"if": "player.health < player.max_health",
            "do": [{"set": {"health": "=player.max_health"}, "on": "player"}, "\"Hold still, Corporal.\" The medic patches you up with a needle and a field dressing. (Health {player.health})"]},
            {"do": ["\"You're good, Corporal. Try to stay that way.\""]}]}},
    "hecu_engineer": {"extends": ["hecu_ally"], "name": "Engineer #hecu_surname#", "proper": True,
        "aliases": ["engineer", "combat engineer", "sapper"], "tags": ["hecu", "ally", "engineer"],
        "appearance": "{self.Name}, a HECU combat engineer, has a cutting torch slung on his back.",
        "description": "A combat engineer with a welding mask pushed up on his helmet.",
        "features": [{"id": "blowtorch", "hidden": True}],
        "actions": {"talk": [{"if": {"not": {"flag": "of_torch_given_{self.uid}"}},
            "do": ["\"Doors giving you grief? Here. Bring it back in one piece.\" He hands you his cutting torch.",
                   {"for_each": "blowtorch", "in": "self", "hidden_too": True, "do": [{"reveal": "it"}, {"move": "it", "to": "player"}]},
                   {"flag": "of_torch_given_{self.uid}"}]},
            {"do": ["\"Cut through anything, that torch. Even regulations.\""]}]}},
})

# ---------------------------------------------------------------------------
# Regions for generated Black Mesa (and beyond) sections
# ---------------------------------------------------------------------------
BM_DIRS = None
R = B.section("regions")
R.update({
    "bm_offices": {"tags": ["scifi", "blackmesa", "office", "indoor", "interior"], "connects": ["blackmesa", "office", "lab", "transit"],
        "length": [2, 3], "distance": [1, 2], "weight": 3,
        "rooms": [
            {"name": "Sector #bm_sector# Office Wing", "description": "#bm_office_desc#", "weight": 3,
             "features": [{"chance": 0.5, "id": "bm_terminal"}, {"chance": 0.3, "id": "vending_machine"}, {"chance": 0.4, "id": "bm_memo"}]},
            {"name": "#bm_department# Offices", "description": "Cubicles in grey fabric run in rows, chairs overturned, monitors still glowing. #bm_office_detail.cap#.",
             "features": [{"chance": 0.6, "id": "bm_terminal"}, {"chance": 0.3, "id": "bm_memo"}]},
            {"name": "Break Room #bm_num#", "description": "A small staff kitchen: a fridge, a microwave, a coffee machine with a burnt pot, a notice about washing your own mug.",
             "features": ["vending_machine", {"chance": 0.4, "id": "medkit"}]},
            {"name": "Conference Room #bm_num#", "description": "A long table, a projector screen showing a frozen slide of quarterly results, and coffee cups abandoned mid-meeting.",
             "features": [{"chance": 0.5, "id": "bm_memo"}]}]},
    "bm_labs": {"tags": ["scifi", "blackmesa", "lab", "indoor", "interior"], "connects": ["blackmesa", "lab", "office", "maintenance"],
        "length": [2, 3], "distance": [1, 2], "weight": 3,
        "rooms": [
            {"name": "#bm_lab_kind# Lab #bm_sector#-#bm_num#", "description": "#bm_lab_desc#", "weight": 3,
             "features": [{"chance": 0.5, "id": "bm_terminal"}, {"chance": 0.3, "id": "health_charger"}]},
            {"name": "Specimen Storage", "description": "Glass tanks line the walls, some cracked and drained. Labels read XEN SAMPLE, DO NOT AGITATE.",
             "features": [{"chance": 0.4, "id": "bm_memo"}]},
            {"name": "Decontamination Bay #bm_num#", "description": "Shower nozzles in a white-tiled booth, a radiation sign and a warning klaxon that has long since given up.",
             "features": [{"chance": 0.3, "id": "suit_charger"}]},
            {"name": "Isotope Handling Room", "description": "Lead-lined cabinets, remote manipulator arms and a glowing green puddle you decide not to step in.",
             "features": [{"chance": 0.4, "id": "supply_crate"}]}]},
    "bm_maintenance": {"tags": ["scifi", "blackmesa", "maintenance", "indoor", "interior"], "connects": ["blackmesa", "maintenance", "storage", "transit", "lab"],
        "length": [2, 4], "distance": [1, 2], "weight": 3,
        "rooms": [
            {"name": "Maintenance Corridor #bm_sector#-#bm_num#", "description": "#bm_maint_desc#", "weight": 3,
             "features": [{"chance": 0.3, "id": "supply_crate"}]},
            {"name": "Pump Station #bm_num#", "description": "Big green pumps thump in a concrete room ankle-deep in water. Pipes sweat overhead.",
             "tags": ["water"]},
            {"name": "Ventilation Shaft", "description": "A cramped sheet-metal duct. You crawl on your elbows; the fan somewhere ahead goes round and round.",
             "features": [{"chance": 0.4, "id": "battery"}]},
            {"name": "Electrical Substation", "description": "Transformers hum behind chain-link. A sign warns DANGER: HIGH VOLTAGE in three languages.",
             "features": [{"chance": 0.4, "id": "suit_charger"}]},
            {"name": "Boiler Room", "description": "Huge boilers roar, gauges trembling in the red. The heat is like a wall.",
             "features": [{"chance": 0.3, "id": "supply_crate"}]}]},
    "bm_transit": {"tags": ["scifi", "blackmesa", "transit", "indoor", "interior"], "connects": ["blackmesa", "transit", "storage", "maintenance"],
        "length": [1, 3], "distance": [2, 3], "weight": 2,
        "rooms": [
            {"name": "Tram Platform #bm_sector#", "description": "A tram platform with yellow safety lines and a dead departures board. The rails vanish into the dark either way.", "weight": 2,
             "features": [{"chance": 0.3, "id": "vending_machine"}]},
            {"name": "Service Tunnel #bm_num#", "description": "A long rail service tunnel lit by caged bulbs. A maintenance cart sits abandoned on a siding."},
            {"name": "Freight Elevator Shaft", "description": "A freight elevator stands open, its cage door bent. Cables vanish up into the dark."}]},
    "bm_storage": {"tags": ["scifi", "blackmesa", "storage", "indoor", "interior"], "connects": ["blackmesa", "storage", "transit", "military"],
        "length": [1, 3], "distance": [1, 2], "weight": 2,
        "rooms": [
            {"name": "Warehouse #bm_sector#", "description": "Shelving stacked to the roof with crates, a forklift parked askew. Somewhere a pallet creaks.", "weight": 2,
             "features": [{"id": "supply_crate", "count": [1, 2]}]},
            {"name": "Loading Dock", "description": "Roller doors, yellow bollards and a ramp down to a truck bay. Everything smells of diesel.",
             "features": [{"chance": 0.5, "id": "supply_crate"}]},
            {"name": "Hazardous Materials Store", "description": "Yellow drums marked with radiation trefoils sit in a chain-link cage. Some are leaking.",
             "features": [{"chance": 0.5, "id": "supply_crate"}]}]},
    "bm_surface": {"tags": ["scifi", "surface", "outdoor", "desert", "blackmesa"], "connects": ["surface", "military", "outdoor"],
        "length": [2, 4], "distance": [2, 4], "weight": 2,
        "rooms": [
            {"name": "#surface_name#", "description": "#surface_desc#", "weight": 3,
             "features": [{"chance": 0.3, "id": "supply_crate"}, {"chance": 0.3, "id": "dead_marine"}]},
            {"name": "Abandoned Checkpoint", "description": "A sandbagged checkpoint on a dusty access road, the barrier arm snapped. A burnt-out humvee smoulders.",
             "features": [{"chance": 0.5, "id": "dead_marine"}]},
            {"name": "Satellite Dish Array", "description": "Huge white dishes stare at the sky on a scrubby ridge, some tilted at mad angles."}]},
    "bm_military": {"tags": ["scifi", "military", "surface", "outdoor"], "connects": ["military", "surface", "storage"],
        "length": [1, 2], "distance": [2, 3], "weight": 1,
        "rooms": [
            {"name": "HECU #camp_kind#", "description": "#camp_desc#", "weight": 2,
             "features": [{"chance": 0.6, "id": "supply_crate"}, {"chance": 0.3, "id": "hecu_logbook"}]},
            {"name": "Sandbag Emplacement", "description": "A ring of sandbags around a mounted machine gun, the gunner gone. Brass casings carpet the ground.",
             "features": [{"chance": 0.4, "id": "ammo_box"}]}]},
    "xen_islands": {"tags": ["scifi", "xen", "alien", "outdoor"], "connects": ["xen", "alien", "racex"],
        "length": [2, 4], "distance": [1, 3], "weight": 2,
        "rooms": [
            {"name": "#xen_name#", "description": "#xen_desc#", "weight": 3,
             "features": [{"chance": 0.4, "id": "xen_light"}, {"chance": 0.2, "id": "xen_glyph"}]},
            {"name": "Xen Healing Grotto", "description": "A cave of soft violet rock around a pool of luminous water.",
             "features": ["healing_pool"]},
            {"name": "Spore Field", "description": "Pod-plants the size of houses pulse slowly, releasing drifting motes of light."}]},
    "border_rift": {"tags": ["seam", "rift", "outdoor", "xen"], "connects": ["rift", "outdoor", "fantasy", "scifi", "road", "surface"],
        "//": "A seam: wherever Black Mesa's world meets another mod's, the resonance cascade has torn the gap open.",
        "length": [1, 2], "distance": [1, 2], "weight": 2,
        "rooms": [
            {"name": "Portal Storm", "description": "Green lightning splits the air, and the land changes in mid-stride: behind you one world, ahead another. Somewhere very far away, a resonance cascade is still ringing.", "weight": 2,
             "features": [{"chance": 0.4, "id": "xen_light"}]},
            {"name": "Rift Scar", "description": "A long scar of glassy, scorched ground where something tore through from elsewhere. Alien light-stalks have already taken root along it, and the air hums.",
             "features": ["xen_light", {"chance": 0.3, "id": "dead_scientist"}]},
            {"name": "Displaced Ground", "description": "A chunk of somewhere else, dropped here whole: a slab of concrete floor with a yellow-and-black hazard stripe, a fallen ceiling light, and a door frame with no walls around it, sitting in the middle of nowhere.",
             "features": [{"chance": 0.5, "id": "supply_crate"}, {"chance": 0.3, "id": "bm_memo"}]}]},
    "racex_hive": {"tags": ["scifi", "racex", "alien", "indoor"], "connects": ["racex", "alien", "xen", "blackmesa"],
        "length": [1, 3], "distance": [1, 2], "weight": 1,
        "rooms": [
            {"name": "Race X Hive", "description": "#racex_desc#", "weight": 2},
            {"name": "Infested Corridor", "description": "A Black Mesa corridor half-swallowed by Race X growth: ribbed, wet, faintly glowing, and humming like a struck wire."}]},
})

# ---------------------------------------------------------------------------
# Obstacles: locked doors and the like, for the story and the map generator
# ---------------------------------------------------------------------------
B.section("obstacles").update({
    "bm_locked_door": {"kind": "barrier", "needs": ["pry", "access"], "tags": ["blackmesa", "indoor", "office", "lab", "maintenance", "storage", "transit"],
        "key": "bm_keycard",
        "feature": {"name": "locked security door", "aliases": ["door", "locked door", "security door"],
            "appearance": [{"if": {"prop": "open"}, "text": "A security door stands open, its lock smashed."},
                           {"text": "A heavy security door is locked here, its keycard reader blinking red."}],
            "description": "Standard Black Mesa blast-rated door. The reader wants a keycard, but the frame looks prisable."},
        "open_text": "You force the lock with {key}. The door grinds open.",
        "locked_text": "It's locked. A keycard, or something to lever it with, would do it.",
        "blocked": "A locked security door bars the way."},
    "bm_jammed_hatch": {"kind": "barrier", "needs": ["pry", "cut"], "tags": ["blackmesa", "maintenance", "storage"],
        "feature": {"name": "jammed hatch", "aliases": ["hatch", "jammed hatch"],
            "appearance": [{"if": {"prop": "open"}, "text": "A maintenance hatch hangs open on bent hinges."},
                           {"text": "A maintenance hatch is jammed in its frame."}],
            "description": "Warped by heat or impact. It needs persuading."},
        "open_text": "You wrench the hatch open with {key}.",
        "locked_text": "It's jammed solid. You need a crowbar or something like it.",
        "blocked": "A jammed hatch blocks the way."},
    "of_welded_door": {"kind": "barrier", "needs": ["cut"], "tags": ["blackmesa", "maintenance", "military"],
        "feature": {"name": "welded door", "aliases": ["door", "welded door", "weld"],
            "appearance": [{"if": {"prop": "open"}, "text": "A door has been cut open; its edges still glow."},
                           {"text": "A steel door has been welded shut, the bead still shiny."}],
            "description": "Someone sealed this from the other side. Only a cutting torch is getting through."},
        "open_text": "You cut a doorway with {key}. The panel falls inward with a clang.",
        "locked_text": "Welded shut. A combat engineer's torch could cut it.",
        "blocked": "A welded door blocks the way."},
    "bm_supply_locker": {"kind": "container", "needs": ["pry", "access"], "tags": ["blackmesa", "military", "storage", "office"],
        "key": "bm_keycard",
        "feature": {"name": "supply locker", "aliases": ["locker", "supply locker", "cabinet"],
            "appearance": [{"if": {"prop": "open"}, "text": "A supply locker hangs open."}, {"text": "A steel supply locker is padlocked here."}],
            "description": "A steel locker with a cheap padlock and a security stencil."},
        "open_text": "You snap the padlock with {key}. The locker swings open.",
        "locked_text": "Padlocked."},
    "xen_chasm": {"kind": "barrier", "needs": ["jump", "grapple"], "tags": ["xen", "alien", "outdoor"],
        "feature": {"name": "chasm", "aliases": ["chasm", "gap", "void", "edge"],
            "appearance": [{"if": {"prop": "open"}, "text": "You've marked a way across the chasm."},
                           {"text": "A gulf of empty violet sky separates this island from the next."}],
            "description": "Far too wide to jump. Unaided."},
        "open_text": "You use {key} to cross the gap, and land rolling on the far side.",
        "locked_text": "It's far too wide to jump without help.",
        "blocked": "The chasm is too wide to cross."},
})

# ---------------------------------------------------------------------------
# Grammar
# ---------------------------------------------------------------------------
B.section("grammar").update({
    "bm_sector": ["A", "B", "C", "D", "E", "F", "G"],
    "bm_num": ["1", "2", "3", "4", "5", "7", "9", "12", "14", "21"],
    "bm_surname": ["Abrams", "Cross", "Green", "Harding", "Keller", "Lorenz", "Marsh", "Okada", "Peralta", "Quill", "Ritter",
                   "Sato", "Thorne", "Underwood", "Vasquez", "Wexler", "Yates", "Zhou", "Pagliacci", "Brannigan"],
    "bm_department": ["Anomalous Materials", "Advanced Biology", "High Energy Research", "Lambda Complex administration",
                      "Hazardous Environment testing", "Applied Physics", "Biological Research", "Materials Science"],
    "bm_lab_kind": ["Spectroscopy", "Biology", "Laser", "Isotope", "Teleportation", "Materials"],
    "bm_lab_desc": ["Lab benches crowded with oscilloscopes and coffee cups. A sample tray lies smashed on the floor. #bm_office_detail.cap#.",
                    "A clean room gone filthy: a centrifuge spins down, a fume hood whines and a whiteboard is covered in equations and a frantic X.",
                    "A long lab under strip lights, with glass-fronted cabinets and a sign that reads AUTHORISED PERSONNEL ONLY."],
    "bm_office_desc": ["A corridor of offices with nameplates and frosted glass. Ceiling panels hang down and a light flickers. #bm_office_detail.cap#.",
                       "An open-plan office in beige and grey. Papers drift across the carpet in the breeze of a broken vent. #bm_office_detail.cap#."],
    "bm_office_detail": ["a phone on a desk rings and rings", "a fluorescent tube buzzes and stutters", "the sprinklers have been going for hours",
                         "a coffee pot has boiled dry on its hotplate", "a radio somewhere plays muzak to nobody", "there are scorch marks where something warped in"],
    "bm_maint_desc": ["A narrow service corridor of exposed pipes and conduit, lit by caged red lamps. Steam vents from a cracked valve.",
                      "Concrete walls stencilled with sector codes, a catwalk over a sump, and a lot of noise from machinery you can't see.",
                      "A cramped access way where ladders and pipe runs meet. Somewhere water drips in a steady, maddening rhythm."],
    "bm_card_colour": ["blue", "red", "yellow", "green", "orange"],
    "ammo_kind": ["box of 9mm rounds", "box of buckshot", "pack of .357 rounds", "box of MP5 magazines", "crate of crossbow bolts",
                  "box of uranium cells", "pack of rifle grenades"],
    "crate_kind": ["supply crate", "wooden crate", "equipment crate"],
    "memo_kind": ["memo", "clipboard", "printout", "staff memo"],
    "bm_terminal_text": ["SYSTEM ERROR: CONTACT IT SUPPORT. IT SUPPORT HAS BEEN CONTACTED. IT SUPPORT IS NOT RESPONDING.",
                         "SECURITY ADVISORY: ALL PERSONNEL REPORT TO THE NEAREST SURFACE EXIT. THIS IS NOT A DRILL.",
                         "Inventory: 1 x sample cart, 1 x crystal sample (GG-3883). Notes: purity unprecedented. Handle with care."],
    "scientist_chatter": ["We have to get to the surface! Someone must have called for help by now.",
                          "I knew this would happen. I said it, at the meeting, and nobody listened.",
                          "Have you seen my colleague? Short, glasses, terrified? No? Of course not.",
                          "If you're going that way, I'm not."],
    "guard_chatter": ["Stay behind me. Or in front of me. Actually, just stay close.",
                      "Whatever you do, don't go back the way I came.",
                      "I'm supposed to be on a break right now.",
                      "Catch me later, I'll buy you a beer."],
    "hecu_rank": ["Private", "Corporal", "Sergeant", "Lance Corporal"],
    "hecu_surname": ["Brady", "Cutter", "Diaz", "Fisk", "Garrity", "Hollis", "Kowalski", "Mendez", "Nash", "Price", "Reyes", "Stone"],
    "hecu_chatter": ["Stay frosty, Corporal.", "Where's that Osprey? Anyone? Anyone?", "Black Ops? Here? That's not good.",
                     "I didn't sign up for aliens.", "Watch your corners."],
    "surface_name": ["#canyon_adj.title# Canyon", "Mesa Ridge", "Dry Wash", "#canyon_adj.title# Overlook", "Access Road #bm_num#"],
    "canyon_adj": ["red", "dusty", "sun-baked", "narrow", "windswept", "scrubby"],
    "surface_desc": ["Red rock walls rise on either side of a dusty wash. The sky is an enormous, merciless blue. Somewhere, helicopters.",
                     "A scrubby mesa top with a view across the desert to the facility's chimneys and dishes. Smoke rises from several of them.",
                     "A dirt road winding between boulders, tyre tracks everywhere, and the smell of cordite."],
    "camp_kind": ["Encampment", "Supply Depot", "Command Post", "Motor Pool"],
    "camp_desc": ["Olive-drab tents, crates of ammunition and a radio table. Somebody left a pot of coffee on a field stove.",
                  "Sandbags, razor wire and a parked humvee. A whiteboard lists grid references and the word CONTAIN, underlined."],
    "xen_name": ["Floating Island", "Xen Outcrop", "Crystal Shelf", "Drifting Rock", "Violet Hollow"],
    "xen_desc": ["A chunk of rock hangs in a swirling green-violet void, other islands drifting at impossible distances. Gravity feels negotiable.",
                 "Spongy alien ground crusted with glowing crystals. Below, there is no below.",
                 "A cliff of pale, porous rock where light-stalks sway. Something enormous moves in the far haze."],
    "racex_desc": ["Walls of glossy organic resin, ribbed like the inside of an animal. Pods twitch and drip.",
                   "A cavern grown rather than built, lit by bioluminescent veins that pulse in time with something huge."],
})

# ---------------------------------------------------------------------------
# Lore shared by all three campaigns
# ---------------------------------------------------------------------------
B.section("lore").update({
    "bm_facility": {"title": "The Black Mesa Research Facility", "about": ["tag:blackmesa"], "tags": ["blackmesa", "history", "security"],
        "text": "Black Mesa is a decommissioned missile base in the New Mexico desert, rebuilt as a sprawling research complex. Most of it is underground, sector after sector, connected by an automated tram system."},
    "bm_hev": {"title": "The HEV suit", "about": ["def:hev_suit"], "tags": ["science", "blackmesa", "hazard"],
        "text": "The Hazardous Environment suit was designed for work around radiation and toxic materials. The Mark IV adds power armour, an injector system and a talkative computer. Nobody designed it for combat. It turned out to be very good at it anyway."},
    "bm_xen": {"title": "Xen", "about": ["tag:xen"], "tags": ["xen", "science", "lambda"],
        "text": "Black Mesa's teleportation research had made contact with another world: a borderworld scientists called Xen, made of floating islands, strange fauna and crystals. Samples were brought back. Some of them were very pure."},
    "bm_lambda": {"title": "The Lambda Complex", "about": ["tag:blackmesa"], "tags": ["lambda", "science", "blackmesa"],
        "text": "The Lambda Complex is Black Mesa's teleportation research centre, built around a reactor big enough to hold a doorway between worlds open."},
    "bm_hecu": {"title": "The HECU", "about": ["tag:military"], "tags": ["hecu", "military", "security"],
        "text": "The Hazardous Environment Combat Unit is a Marine Corps formation trained for chemical, biological and other unusual battlefields. Their orders at Black Mesa were to contain the incident. Their orders said nothing about survivors."},
    "bm_black_ops": {"title": "The Black Ops", "about": ["mod:hl_core"], "tags": ["hecu", "military", "black_ops"], "chance": 0.8,
        "text": "Black-clad operatives arrived after the Marines: silent, acrobatic, answering to nobody anyone can name. They didn't come to contain. They came to erase."},
    "bm_tram": {"title": "The tram system", "about": ["tag:transit"], "tags": ["blackmesa", "transit", "security"],
        "text": "The Black Mesa Transit System runs automated trams between sectors. Its recorded announcer is cheerful about everything, including the facility's mandatory radiation safety training."},
    "bm_headcrab": {"title": "Headcrabs", "about": ["def:headcrab"], "tags": ["xen", "science"],
        "text": "Headcrabs are Xen parasites. They leap for the head of a host and take over its nervous system. The result is a zombie. The host may still be aware. Nobody wants to think about that."},
    "bm_vortigaunt": {"title": "Vortigaunts", "about": ["def:vortigaunt"], "tags": ["xen", "science"],
        "text": "The vortigaunts wear collars and shackles. Whoever is sending them through, they are not volunteers."},
    "bm_racex": {"title": "Race X", "about": ["tag:racex"], "tags": ["racex", "xen", "hecu"], "chance": 0.9,
        "text": "Not everything coming through the rifts is from Xen. A second alien race - shock troopers, pit drones, voltigores - is using the chaos to invade. The soldiers started calling them Race X."},
})

# Lore that only exists when Black Mesa shares a world with another mod's places.
B.section("lore").update({
    "hl_rifts": {"title": "The rifts", "about": ["tag:rift"], "tags": ["xen", "science", "rumour"],
        "text": "Since the resonance cascade, the walls between worlds have worn thin. Where one world rubs against another, the ground tears open in green lightning, and things cross in both directions."},
    "hl_x_hamlet": {"title": "The night the sky turned green", "about": ["mod:hamlet", "tag:blackmesa"], "tags": ["village", "rumour", "xen", "history"],
        "text": "Old folk in the village still talk about the night the sky over the hills turned green, and a stooped thing with one red eye and crackling hands came down to drink at the well. By morning it was gone, and so was the miller's dog."},
    "hl_x_wilds": {"title": "Soldiers in the hills", "about": ["mod:wilds", "tag:blackmesa"], "tags": ["rumour", "road", "hecu", "military"],
        "text": "Travellers on the roads talk of soldiers in gas masks camped up in the hills, who stop every stranger to ask the same question: have you seen a scientist in an orange suit?"},
    "hl_x_derelict": {"title": "A signal from somewhere else", "about": ["mod:derelict", "tag:blackmesa"], "tags": ["station", "science", "xen", "comms"],
        "text": "Station Kestrel's comms log holds one transmission nobody could explain: a burst on an old Earth research frequency, headed LAMBDA, repeating a single word. The word is 'Xen'."},
    "hl_x_barrow": {"title": "The carvings below", "about": ["mod:barrow", "tag:xen"], "tags": ["ancient", "history", "xen"],
        "text": "Deep in the barrow, the oldest carvings show something no one has explained: islands floating under a strange sky, and a vast head with a crown of crystals. Whoever cut them had seen it, or dreamed it very clearly."},
    "hl_x_spire": {"title": "Harmonic coupling", "about": ["mod:spire", "tag:lambda"], "tags": ["science", "xen", "sorcery", "darkness"],
        "text": "A Lambda team memo, found far from any lab: 'Sample resonates with an object of unknown origin at the same frequency. Recommend we do NOT put them in the same room.' Someone has scrawled under it: the sorcerer's orb."},
    "hl_x_lighthouse": {"title": "The green beam", "about": ["mod:lighthouse", "tag:blackmesa"], "tags": ["coast", "rumour", "xen"],
        "text": "Fishermen swear that one night the lighthouse's beam turned green, swept once across a sea that wasn't there, and went out."},
})

B.section("events").update({
    "hl_incursion": {
        "//": "Black Mesa's story for worlds that begin somewhere else: the rifts lead back to the source.",
        "title": ["Incursion", "The Green Sky", "Resonance"],
        "tags": ["xen", "incursion", "rift", "crossover"], "exclude_start_tags": ["blackmesa", "hecu"], "weight": 1.5,
        "roles": {
            "villain": {"type": "character", "match": {"tag": ["rift_lord"]}},
            "facility": {"type": "place", "match": {"tag": ["bm_main"]}}},
        "hook": "Green lightning splits the sky. Where it strikes, the ground tears open, and things that have no business in this world come crawling out: scuttling parasites, yelping three-legged hounds, worse. Nobody knows what they are. The truth is a long way off, in {facility}, where an experiment went catastrophically wrong, and beyond it waits {villain}, holding the rifts open.",
        "goal": "Follow the rifts to {facility}, and destroy {villain} to close them.",
        "resolutions": [{"verb": "attack", "target": "villain", "title": "Close the rifts",
                         "text": "{target.The} dies, and all across the world the green lightning gutters out. The rifts heal over as if they had never been."}],
        "lore": [{"title": "Where the rifts lead", "about": ["cast:facility"],
                  "text": "Every rift, followed far enough, leads to the same place: {facility}, a research complex where someone pushed a crystal into a beam and tore a hole between worlds."}],
        "ending": "The sky is the right colour again. In a year people will say the rifts were a story. You will know better."},
})

B.section("rules").update({
    "hl_combat_hint": {"on": "start", "if": {"mod": "hl_core"}, "do": [{"say": "(Things from Black Mesa bite. 'attack <enemy> [with <weapon>]', 'status' or 'suit' for your health and armour, and 'use' chargers and batteries.)", "style": "dim"}]},
})

B.section("verbs").update({
    "turn": {"aliases": ["spin", "rotate", "twist", "crank"], "help": "turn <thing>",
             "default": ["Turning {target} achieves nothing."]},
    "where": {"aliases": ["chapter", "mapinfo", "which map", "location"], "target": "none", "time": 0, "help": "where",
              "default": [{"if": {"prop": "map", "of": "room", "ne": ""},
                           "then": ["{room.name}: {room.chapter} (map {room.map})."],
                           "else": ["{room.name}. Not on any map you know."]}]},
    "suit": {"aliases": ["hev", "armour", "armor"], "target": "none", "time": 0, "help": "suit",
             "default": ["Health {player.health}/{player.max_health}. Suit {player.suit}/{player.max_suit}."]},
})

B.section("macros").update(MACROS)


def build():
    manifest = {
        "id": "hl_core", "name": "Black Mesa: Core", "version": "1.0.0", "author": "Patchwork",
        "description": "Shared content for the Half-Life, Opposing Force and Blue Shift mods: every weapon (crowbar to displacer cannon), item, creature and person from the three games, suit armour, health and HEV chargers, breakable crates, procedurally generated Black Mesa offices, labs, maintenance tunnels, transit, the desert surface, military camps, Xen and Race X hives, locked doors for the map generator, and Black Mesa lore.",
        "requires": ["core", "combat"], "load_after": ["combat"], "recommends": ["hl_halflife", "hl_opfor", "hl_blueshift"],
        "priority": 62, "tags": ["half-life", "blackmesa", "scifi", "content"],
    }
    B.write(manifest, {
        "weapons.json": {"features": {k: v for k, v in F.items() if k in W}},
        "items.json": {"features": {k: v for k, v in F.items() if k not in W and k not in C}},
        "creatures.json": {"features": C},
        "regions.json": {"regions": B.sections["regions"], "obstacles": B.sections["obstacles"]},
        "text.json": {"grammar": B.sections["grammar"], "lore": B.sections["lore"], "rules": B.sections["rules"], "events": B.sections["events"],
                      "verbs": B.sections["verbs"], "macros": B.sections["macros"]},
    })
