"""
Kanto Pokédex data used by generate.py.

Each entry:
  num, id, display name, types, base stats (HP, Atk, Def, Spc, Spe),
  weight (kg), evolutions, habitats, rarity, catch tier, symbol, color, description

Evolution strings:
  "L16:ivysaur"      level-up evolution at level 16
  "S:fire:flareon"   evolution stone (fire, water, thunder, leaf, moon)
  "T:golem"          trade evolution; in this mod done with a Link Cable item

Habitats map onto spawn groups in generate.py:
  forest, field, water, ocean, cave, mountain, urban, sewer, swamp,
  power, lab, safari, special (never spawns naturally)

Rarity: common / uncommon / rare / none
Catch tier: 1 (easy) .. 4 (legendary), loosely based on the Gen 1 catch rates.
Base stats are the Generation I values (Special is a single stat).
Descriptions are written for this mod: the Pokémon of Kanto as they might
behave after the Cataclysm.
"""

POKEDEX = [
    (1, "bulbasaur", "Bulbasaur", ["grass", "poison"], (45, 49, 49, 65, 45), 6.9, ["L16:ivysaur"], ["forest", "field"], "rare", 3, "B", "light_green",
     "A small, four-legged Pokémon with a plant bulb on its back.  The bulb soaks up sunlight even through the haze over the ruined cities, and it seems content to nap in overgrown gardens."),
    (2, "ivysaur", "Ivysaur", ["grass", "poison"], (60, 62, 63, 80, 60), 13.0, ["L32:venusaur"], ["forest"], "rare", 3, "B", "green",
     "The bulb on this Pokémon's back has budded into a heavy flower.  It plants itself in sunny clearings and lashes out with vines when disturbed."),
    (3, "venusaur", "Venusaur", ["grass", "poison"], (80, 82, 83, 100, 80), 100.0, [], ["forest"], "none", 3, "B", "light_green",
     "A huge, squat Pokémon crowned with a blooming flower that gives off a soothing scent.  Even the dead seem to hesitate near it."),
    (4, "charmander", "Charmander", ["fire"], (39, 52, 43, 50, 65), 8.5, ["L16:charmeleon"], ["mountain", "field"], "rare", 3, "C", "light_red",
     "A small, bipedal lizard with a flame burning at the tip of its tail.  The flame flickers with its mood and is said to go out only when it dies."),
    (5, "charmeleon", "Charmeleon", ["fire"], (58, 64, 58, 65, 80), 19.0, ["L36:charizard"], ["mountain"], "rare", 3, "C", "red",
     "A hot-tempered, claw-swinging lizard.  When riled up, the flame on its tail flares to a bluish white."),
    (6, "charizard", "Charizard", ["fire", "flying"], (78, 84, 78, 85, 100), 90.5, [], ["mountain"], "none", 3, "C", "light_red",
     "A winged, dragon-like Pokémon that breathes fire hot enough to melt boulders.  It only picks fights with opponents worth fighting."),
    (7, "squirtle", "Squirtle", ["water"], (44, 48, 65, 50, 43), 9.0, ["L16:wartortle"], ["water", "swamp"], "rare", 3, "S", "light_blue",
     "A small turtle Pokémon that retreats into its shell and fires jets of water from its mouth."),
    (8, "wartortle", "Wartortle", ["water"], (59, 63, 80, 65, 58), 22.5, ["L36:blastoise"], ["water"], "rare", 3, "S", "blue",
     "A turtle Pokémon with a furry, feathery tail.  It hides near rivers and paddles out to ambush the shamblers that wander too close."),
    (9, "blastoise", "Blastoise", ["water"], (79, 83, 100, 85, 78), 85.5, [], ["water"], "none", 3, "S", "blue",
     "A heavy, armored turtle with pressurized water cannons jutting from its shell.  Its blasts can punch through concrete."),
    (10, "caterpie", "Caterpie", ["bug"], (45, 30, 35, 20, 45), 2.9, ["L7:metapod"], ["forest", "field"], "common", 1, "c", "green",
     "A green, worm-like Pokémon.  The red antenna on its head releases a terrible stench to repel predators."),
    (11, "metapod", "Metapod", ["bug"], (50, 20, 55, 25, 30), 9.9, ["L10:butterfree"], ["forest"], "common", 1, "c", "light_green",
     "A hardened cocoon.  It barely moves, waiting for the day its body is ready to emerge."),
    (12, "butterfree", "Butterfree", ["bug", "flying"], (60, 45, 50, 80, 70), 32.0, [], ["forest", "field"], "uncommon", 2, "B", "white",
     "A large butterfly Pokémon whose wings scatter sleep-inducing powder."),
    (13, "weedle", "Weedle", ["bug", "poison"], (40, 35, 30, 20, 50), 3.2, ["L7:kakuna"], ["forest"], "common", 1, "w", "brown",
     "A hairy bug with a sharp, venomous stinger on its head.  It hides in tall grass and leaf litter."),
    (14, "kakuna", "Kakuna", ["bug", "poison"], (45, 25, 50, 25, 35), 10.0, ["L10:beedrill"], ["forest"], "common", 1, "k", "yellow",
     "A nearly motionless cocoon.  It can still extend a poison barb when threatened."),
    (15, "beedrill", "Beedrill", ["bug", "poison"], (65, 80, 40, 45, 75), 29.5, [], ["forest"], "uncommon", 2, "B", "yellow",
     "A wasp-like Pokémon with venomous stingers on its forelegs and tail.  Swarms of them attack anything that strays near their nests."),
    (16, "pidgey", "Pidgey", ["normal", "flying"], (40, 45, 40, 35, 56), 1.8, ["L18:pidgeotto"], ["field", "forest", "urban"], "common", 1, "p", "brown",
     "A common, docile bird Pokémon.  Flocks of Pidgey still pick through abandoned lots for seeds and bugs."),
    (17, "pidgeotto", "Pidgeotto", ["normal", "flying"], (63, 60, 55, 50, 71), 30.0, ["L36:pidgeot"], ["field", "forest"], "uncommon", 2, "p", "light_red",
     "A territorial bird Pokémon with sharp talons that can carry off prey from a great distance."),
    (18, "pidgeot", "Pidgeot", ["normal", "flying"], (83, 80, 75, 70, 91), 39.5, [], ["field"], "rare", 2, "P", "yellow",
     "A magnificent bird Pokémon with glossy plumage.  It can fly at twice the speed of sound."),
    (19, "rattata", "Rattata", ["normal"], (30, 56, 35, 25, 72), 3.5, ["L20:raticate"], ["urban", "sewer", "field"], "common", 1, "r", "magenta",
     "A small rodent Pokémon with big fangs.  The collapse of the cities has been very good to Rattata."),
    (20, "raticate", "Raticate", ["normal"], (55, 81, 60, 50, 97), 18.5, [], ["urban", "sewer"], "uncommon", 2, "R", "brown",
     "Its whiskers help it keep its balance, and its ever-growing fangs can gnaw through brick and rebar."),
    (21, "spearow", "Spearow", ["normal", "flying"], (40, 60, 30, 31, 70), 2.0, ["L20:fearow"], ["field", "urban"], "common", 1, "s", "brown",
     "A small, aggressive bird Pokémon that flaps its short wings frantically to stay airborne."),
    (22, "fearow", "Fearow", ["normal", "flying"], (65, 90, 65, 61, 100), 38.0, [], ["field"], "uncommon", 2, "F", "brown",
     "A large bird Pokémon with a long neck and beak.  It can stay aloft for a whole day without landing."),
    (23, "ekans", "Ekans", ["poison"], (35, 60, 44, 40, 55), 6.9, ["L22:arbok"], ["field", "swamp"], "common", 1, "e", "magenta",
     "A purple snake Pokémon that moves silently through grass and swallows bird eggs whole."),
    (24, "arbok", "Arbok", ["poison"], (60, 85, 69, 65, 80), 65.0, [], ["field", "swamp"], "uncommon", 2, "A", "magenta",
     "A cobra Pokémon with a frightening pattern on its hood that paralyzes foes with fear."),
    (25, "pikachu", "Pikachu", ["electric"], (35, 55, 30, 50, 90), 6.0, ["S:thunder:raichu"], ["forest", "power"], "rare", 2, "P", "yellow",
     "A mouse Pokémon that stores electricity in the red pouches on its cheeks.  Groups of them gather around the dead power lines, which still hum when they are near."),
    (26, "raichu", "Raichu", ["electric"], (60, 90, 55, 90, 100), 30.0, [], ["power"], "none", 2, "R", "yellow",
     "When its electricity builds up, its muscles stiffen and it becomes aggressive.  Its tail acts as a ground."),
    (27, "sandshrew", "Sandshrew", ["ground"], (50, 75, 85, 30, 40), 12.0, ["L22:sandslash"], ["field", "mountain"], "common", 1, "s", "yellow",
     "A Pokémon that burrows deep into dry soil and curls into a ball to protect itself."),
    (28, "sandslash", "Sandslash", ["ground"], (75, 100, 110, 55, 65), 29.5, [], ["mountain"], "uncommon", 2, "S", "brown",
     "Its back is covered in tough spikes.  It curls up and rolls at its enemies."),
    (29, "nidoran_f", "Nidoran♀", ["poison"], (55, 47, 52, 40, 41), 7.0, ["L16:nidorina"], ["field", "safari"], "common", 1, "n", "light_blue",
     "A small, cautious Pokémon with poisonous barbs.  The female's horn is smaller than the male's."),
    (30, "nidorina", "Nidorina", ["poison"], (70, 62, 67, 55, 56), 20.0, ["S:moon:nidoqueen"], ["field", "safari"], "uncommon", 2, "n", "cyan",
     "A gentle Pokémon that retracts its barbs when relaxed among friends."),
    (31, "nidoqueen", "Nidoqueen", ["poison", "ground"], (90, 82, 87, 75, 76), 60.0, [], ["safari"], "none", 2, "N", "blue",
     "Its body is covered in hard, needle-like scales.  It is at its most ferocious defending its young."),
    (32, "nidoran_m", "Nidoran♂", ["poison"], (46, 57, 40, 40, 50), 9.0, ["L16:nidorino"], ["field", "safari"], "common", 1, "n", "magenta",
     "A small Pokémon with large ears and a venomous horn."),
    (33, "nidorino", "Nidorino", ["poison"], (61, 72, 57, 55, 65), 19.5, ["S:moon:nidoking"], ["field", "safari"], "uncommon", 2, "n", "pink",
     "An aggressive Pokémon that is quick to attack.  Its horn is harder than a diamond."),
    (34, "nidoking", "Nidoking", ["poison", "ground"], (81, 92, 77, 75, 85), 62.0, [], ["safari"], "none", 2, "N", "magenta",
     "A brutish Pokémon that swings its thick tail like a club.  Its horn injects potent venom."),
    (35, "clefairy", "Clefairy", ["normal"], (70, 45, 48, 60, 35), 7.5, ["S:moon:clefable"], ["cave", "mountain"], "rare", 2, "c", "pink",
     "A rare, adorable Pokémon that is said to come from the moon.  It is often seen dancing on clear nights."),
    (36, "clefable", "Clefable", ["normal"], (95, 70, 73, 85, 60), 40.0, [], ["mountain"], "none", 2, "C", "pink",
     "A timid fairy Pokémon that is rarely seen.  It flees when it senses people."),
    (37, "vulpix", "Vulpix", ["fire"], (38, 41, 40, 65, 65), 9.9, ["S:fire:ninetales"], ["field", "urban"], "uncommon", 2, "v", "red",
     "A fox Pokémon born with a single white tail that splits into six beautiful curled tails as it grows."),
    (38, "ninetales", "Ninetales", ["fire"], (73, 76, 75, 100, 100), 19.9, [], ["field"], "none", 2, "N", "yellow",
     "A very intelligent and vengeful fox Pokémon.  Legends say it can live for a thousand years."),
    (39, "jigglypuff", "Jigglypuff", ["normal"], (115, 45, 20, 25, 20), 5.5, ["S:moon:wigglytuff"], ["field", "urban"], "uncommon", 1, "j", "pink",
     "A round, balloon-like Pokémon that sings a mysterious lullaby.  Even zombies seem to stagger to a halt when it sings."),
    (40, "wigglytuff", "Wigglytuff", ["normal"], (140, 70, 45, 50, 45), 12.0, [], ["field"], "none", 2, "W", "pink",
     "A balloon Pokémon with a fine, soft coat.  Its body can inflate to an enormous size."),
    (41, "zubat", "Zubat", ["poison", "flying"], (40, 45, 35, 40, 55), 7.5, ["L22:golbat"], ["cave", "sewer"], "common", 1, "z", "blue",
     "An eyeless bat Pokémon that navigates using ultrasonic waves.  The tunnels under the cities are full of them."),
    (42, "golbat", "Golbat", ["poison", "flying"], (75, 80, 70, 75, 90), 55.0, [], ["cave"], "uncommon", 2, "Z", "blue",
     "A bat Pokémon with a huge mouth.  Once it bites, it drains blood until it can barely fly."),
    (43, "oddish", "Oddish", ["grass", "poison"], (45, 50, 55, 75, 30), 5.4, ["L21:gloom"], ["field", "forest"], "common", 1, "o", "green",
     "A weed-like Pokémon that buries itself in soil by day and wanders at night, scattering seeds."),
    (44, "gloom", "Gloom", ["grass", "poison"], (60, 65, 70, 85, 40), 8.6, ["S:leaf:vileplume"], ["field", "forest"], "uncommon", 2, "g", "blue",
     "It drools a sticky, foul-smelling nectar.  The stench is strong enough to be smelled a mile away."),
    (45, "vileplume", "Vileplume", ["grass", "poison"], (75, 80, 85, 100, 50), 18.6, [], ["forest"], "none", 2, "V", "red",
     "Its flower petals are the largest in the world.  It scatters toxic pollen with every step."),
    (46, "paras", "Paras", ["bug", "grass"], (35, 70, 55, 55, 25), 5.4, ["L24:parasect"], ["forest", "cave"], "common", 1, "p", "light_red",
     "A bug Pokémon with mushrooms called tochukaso growing on its back.  The mushrooms feed on the host."),
    (47, "parasect", "Parasect", ["bug", "grass"], (60, 95, 80, 80, 30), 29.5, [], ["forest", "cave"], "uncommon", 2, "P", "red",
     "A bug Pokémon controlled by the giant mushroom on its back.  It prefers damp, dark places, and fungal growths spread wherever it lives."),
    (48, "venonat", "Venonat", ["bug", "poison"], (60, 55, 50, 40, 45), 30.0, ["L31:venomoth"], ["forest"], "common", 1, "v", "magenta",
     "Its large compound eyes act as radar.  It is drawn to lights at night."),
    (49, "venomoth", "Venomoth", ["bug", "poison"], (70, 65, 60, 90, 90), 12.5, [], ["forest"], "uncommon", 2, "V", "magenta",
     "A moth Pokémon whose wings are covered in poisonous dust that causes paralysis."),
    (50, "diglett", "Diglett", ["ground"], (10, 55, 25, 45, 95), 0.8, ["L26:dugtrio"], ["cave", "field"], "common", 1, "d", "brown",
     "A mole Pokémon that lives about one yard underground.  Farmers once prized it for tilling soil."),
    (51, "dugtrio", "Dugtrio", ["ground"], (35, 80, 50, 70, 120), 33.3, [], ["cave"], "uncommon", 2, "D", "brown",
     "A team of Diglett triplets.  It triggers huge earthquakes by burrowing a hundred miles underground."),
    (52, "meowth", "Meowth", ["normal"], (40, 45, 35, 40, 90), 4.2, ["L28:persian"], ["urban"], "common", 1, "m", "yellow",
     "A cat Pokémon that loves shiny coins.  It still hoards them, even though money barely means anything anymore."),
    (53, "persian", "Persian", ["normal"], (65, 70, 60, 65, 115), 32.0, [], ["urban"], "uncommon", 2, "P", "yellow",
     "A sleek, haughty cat Pokémon.  It is very difficult to raise because of its fickle temperament."),
    (54, "psyduck", "Psyduck", ["water"], (50, 52, 48, 50, 55), 19.6, ["L33:golduck"], ["water", "swamp"], "common", 1, "p", "yellow",
     "A duck Pokémon constantly troubled by headaches.  When they get too bad, it unleashes strange powers."),
    (55, "golduck", "Golduck", ["water"], (80, 82, 78, 80, 85), 76.6, [], ["water"], "uncommon", 2, "G", "blue",
     "A graceful swimmer often seen in lakes at dawn.  It is sometimes mistaken for a cryptid."),
    (56, "mankey", "Mankey", ["fighting"], (40, 80, 35, 35, 70), 28.0, ["L28:primeape"], ["mountain", "forest"], "common", 1, "m", "white",
     "An extremely quick-tempered pig monkey Pokémon.  It flies into a rage at the slightest provocation."),
    (57, "primeape", "Primeape", ["fighting"], (65, 105, 60, 60, 95), 32.0, [], ["mountain"], "uncommon", 2, "P", "white",
     "It is always furious.  It chases anyone who looks at it and pummels them relentlessly."),
    (58, "growlithe", "Growlithe", ["fire"], (55, 70, 45, 50, 60), 19.0, ["S:fire:arcanine"], ["urban", "field"], "uncommon", 2, "g", "light_red",
     "A loyal puppy Pokémon.  Many were kept by police departments before the end, and some still guard their empty precincts."),
    (59, "arcanine", "Arcanine", ["fire"], (90, 110, 80, 80, 95), 155.0, [], ["field"], "none", 2, "A", "light_red",
     "A legendary-looking Pokémon of great beauty.  It can run more than six thousand miles in a single day."),
    (60, "poliwag", "Poliwag", ["water"], (40, 50, 40, 40, 90), 12.4, ["L25:poliwhirl"], ["water", "swamp"], "common", 1, "p", "blue",
     "A tadpole Pokémon whose skin is so thin its spiral-shaped organs show through."),
    (61, "poliwhirl", "Poliwhirl", ["water"], (65, 65, 65, 50, 90), 20.0, ["S:water:poliwrath"], ["water", "swamp"], "uncommon", 2, "P", "blue",
     "It can live on land or in water.  Staring at the spiral on its belly makes people drowsy."),
    (62, "poliwrath", "Poliwrath", ["water", "fighting"], (90, 85, 95, 70, 70), 54.0, [], ["water"], "none", 2, "P", "light_blue",
     "A powerful swimmer with tremendous muscles.  It can cross oceans using only the breaststroke."),
    (63, "abra", "Abra", ["psychic"], (25, 20, 15, 105, 90), 19.5, ["L16:kadabra"], ["urban", "cave"], "uncommon", 3, "a", "yellow",
     "A Pokémon that sleeps eighteen hours a day.  It teleports away the moment it senses danger."),
    (64, "kadabra", "Kadabra", ["psychic"], (40, 35, 30, 120, 105), 56.5, ["T:alakazam"], ["urban"], "rare", 3, "K", "yellow",
     "It emits powerful alpha waves that cause headaches.  Electronics fail around it."),
    (65, "alakazam", "Alakazam", ["psychic"], (55, 50, 45, 135, 120), 48.0, [], ["urban"], "none", 3, "A", "yellow",
     "Its brain never stops growing.  It remembers everything that has happened to it since the moment it was born."),
    (66, "machop", "Machop", ["fighting"], (70, 80, 50, 35, 35), 19.5, ["L28:machoke"], ["mountain", "urban"], "common", 1, "m", "light_gray",
     "A superhumanly strong Pokémon that trains by lifting rubble from collapsed buildings."),
    (67, "machoke", "Machoke", ["fighting"], (80, 100, 70, 50, 45), 70.5, ["T:machamp"], ["mountain"], "uncommon", 2, "M", "light_gray",
     "Its muscular body is so powerful it must wear a power-save belt to regulate its strength."),
    (68, "machamp", "Machamp", ["fighting"], (90, 130, 80, 65, 55), 130.0, [], ["mountain"], "none", 2, "M", "dark_gray",
     "With four arms it throws a thousand punches in two seconds.  It can hurl a car."),
    (69, "bellsprout", "Bellsprout", ["grass", "poison"], (50, 75, 35, 70, 40), 4.0, ["L21:weepinbell"], ["field", "forest"], "common", 1, "b", "light_green",
     "A carnivorous plant Pokémon that snares insects with its vines."),
    (70, "weepinbell", "Weepinbell", ["grass", "poison"], (65, 90, 50, 85, 55), 6.4, ["S:leaf:victreebel"], ["forest"], "uncommon", 2, "W", "green",
     "It spits a fluid that dissolves anything, then sucks up the remains."),
    (71, "victreebel", "Victreebel", ["grass", "poison"], (80, 105, 65, 100, 70), 15.5, [], ["forest"], "none", 2, "V", "green",
     "It lures prey into its gaping mouth with the sweet scent of honey, then melts them down."),
    (72, "tentacool", "Tentacool", ["water", "poison"], (40, 40, 35, 100, 70), 45.5, ["L30:tentacruel"], ["ocean"], "common", 1, "t", "light_blue",
     "A jellyfish Pokémon that drifts in shallow seas.  Swimmers who stumble across one are stung."),
    (73, "tentacruel", "Tentacruel", ["water", "poison"], (80, 70, 65, 120, 100), 55.0, [], ["ocean"], "uncommon", 2, "T", "blue",
     "It has eighty tentacles that it extends to capture prey and drench it in poison."),
    (74, "geodude", "Geodude", ["rock", "ground"], (40, 80, 100, 30, 20), 20.0, ["L25:graveler"], ["cave", "mountain"], "common", 1, "g", "light_gray",
     "A rock Pokémon often found on mountain trails.  People sometimes trip over Geodude, mistaking them for boulders."),
    (75, "graveler", "Graveler", ["rock", "ground"], (55, 95, 115, 45, 35), 105.0, ["T:golem"], ["cave", "mountain"], "uncommon", 2, "G", "light_gray",
     "It rolls down slopes to move, heedless of anything in its way."),
    (76, "golem", "Golem", ["rock", "ground"], (80, 110, 130, 55, 45), 300.0, [], ["mountain"], "none", 2, "G", "dark_gray",
     "Its boulder-like body is extremely hard.  It sheds its skin once a year and the old shell crumbles to gravel."),
    (77, "ponyta", "Ponyta", ["fire"], (50, 85, 55, 65, 90), 30.0, ["L40:rapidash"], ["field"], "uncommon", 2, "p", "yellow",
     "A horse Pokémon with a fiery mane.  Its hooves are ten times harder than diamonds."),
    (78, "rapidash", "Rapidash", ["fire"], (65, 100, 70, 80, 105), 95.0, [], ["field"], "rare", 2, "R", "yellow",
     "Very competitive, it chases anything that moves fast, even cars, in hopes of racing it."),
    (79, "slowpoke", "Slowpoke", ["water", "psychic"], (90, 65, 65, 40, 15), 36.0, ["L37:slowbro"], ["water", "ocean"], "common", 1, "s", "pink",
     "Incredibly slow and dopey.  It takes five seconds for it to feel pain when attacked."),
    (80, "slowbro", "Slowbro", ["water", "psychic"], (95, 75, 110, 80, 30), 78.5, [], ["ocean"], "uncommon", 2, "S", "pink",
     "A Shellder bit onto its tail and refuses to let go.  It does not seem to mind."),
    (81, "magnemite", "Magnemite", ["electric"], (25, 35, 70, 95, 45), 6.0, ["L30:magneton"], ["power", "urban"], "common", 1, "m", "light_gray",
     "It floats using electromagnetic waves.  It is drawn to dead generators and fried transformers."),
    (82, "magneton", "Magneton", ["electric"], (50, 60, 95, 120, 70), 60.0, [], ["power"], "uncommon", 2, "M", "light_gray",
     "Three Magnemite linked together.  It scrambles radio signals and makes the air tingle."),
    (83, "farfetchd", "Farfetch'd", ["normal", "flying"], (52, 65, 55, 58, 60), 15.0, [], ["field", "swamp"], "rare", 2, "f", "brown",
     "A wild duck Pokémon that always carries a plant stalk.  It fights fiercely to protect it."),
    (84, "doduo", "Doduo", ["normal", "flying"], (35, 85, 45, 35, 75), 39.2, ["L31:dodrio"], ["field", "safari"], "common", 1, "d", "brown",
     "A two-headed bird Pokémon that runs instead of flying.  The two heads are said to share a single brain."),
    (85, "dodrio", "Dodrio", ["normal", "flying"], (60, 110, 70, 60, 100), 85.2, [], ["safari"], "uncommon", 2, "D", "brown",
     "A three-headed bird.  The heads express joy, sorrow, and anger, and never all at once."),
    (86, "seel", "Seel", ["water"], (65, 45, 55, 70, 45), 90.0, ["L34:dewgong"], ["ocean"], "uncommon", 2, "s", "white",
     "A sea lion Pokémon that loves freezing cold water.  Its hide is extremely tough."),
    (87, "dewgong", "Dewgong", ["water", "ice"], (90, 70, 80, 95, 70), 120.0, [], ["ocean"], "rare", 2, "D", "white",
     "Its body is covered in pure white fur.  It stores heat in its body to swim through frigid seas."),
    (88, "grimer", "Grimer", ["poison"], (80, 80, 50, 40, 25), 30.0, ["L38:muk"], ["sewer", "urban"], "common", 1, "g", "magenta",
     "Sludge exposed to the X-rays of a dead world became this Pokémon.  It thrives in the chemical runoff of the ruined cities."),
    (89, "muk", "Muk", ["poison"], (105, 105, 75, 65, 50), 30.0, [], ["sewer"], "uncommon", 2, "M", "magenta",
     "A living mass of sludge.  Plants won't grow where it has crawled, and the stench is unbearable."),
    (90, "shellder", "Shellder", ["water"], (30, 65, 100, 45, 40), 4.0, ["S:water:cloyster"], ["ocean"], "common", 1, "s", "magenta",
     "Its hard shell repels any attack.  It is vulnerable only when its shell is open."),
    (91, "cloyster", "Cloyster", ["water", "ice"], (50, 95, 180, 85, 70), 132.5, [], ["ocean"], "none", 2, "C", "magenta",
     "A bivalve Pokémon with a shell harder than steel.  It shoots spikes at attackers."),
    (92, "gastly", "Gastly", ["ghost", "poison"], (30, 35, 30, 100, 80), 1.0, ["L25:haunter"], ["urban", "cave"], "uncommon", 2, "g", "magenta",
     "A Pokémon made almost entirely of poisonous gas.  It haunts abandoned buildings, which there is now no shortage of."),
    (93, "haunter", "Haunter", ["ghost", "poison"], (45, 50, 45, 115, 95), 1.0, ["T:gengar"], ["urban"], "rare", 2, "H", "magenta",
     "Because of its ability to slip through walls, it is said to come from another dimension."),
    (94, "gengar", "Gengar", ["ghost", "poison"], (60, 65, 60, 130, 110), 40.5, [], ["urban"], "none", 2, "G", "magenta",
     "Under a full moon it mimics the shadows of people and laughs at their fright."),
    (95, "onix", "Onix", ["rock", "ground"], (35, 45, 160, 30, 70), 210.0, [], ["cave", "mountain"], "uncommon", 2, "O", "light_gray",
     "A giant rock snake Pokémon that tunnels underground at fifty miles an hour, leaving tunnels behind."),
    (96, "drowzee", "Drowzee", ["psychic"], (60, 48, 45, 90, 42), 32.4, ["L26:hypno"], ["urban", "field"], "common", 1, "d", "yellow",
     "It puts enemies to sleep and then eats their dreams.  Survivors who wake up feeling drained blame it."),
    (97, "hypno", "Hypno", ["psychic"], (85, 73, 70, 115, 67), 75.6, [], ["urban"], "uncommon", 2, "H", "yellow",
     "It carries a pendulum-like device.  Avoid eye contact when it swings."),
    (98, "krabby", "Krabby", ["water"], (30, 105, 90, 25, 50), 6.5, ["L28:kingler"], ["ocean", "water"], "common", 1, "k", "light_red",
     "A crab Pokémon that lives near the shore.  Its pincers regrow if they are torn off."),
    (99, "kingler", "Kingler", ["water"], (55, 130, 115, 50, 75), 60.0, [], ["ocean"], "uncommon", 2, "K", "light_red",
     "Its oversized claw has ten thousand horsepower of crushing force.  It is too heavy to swing quickly."),
    (100, "voltorb", "Voltorb", ["electric"], (40, 30, 50, 55, 100), 10.4, ["L30:electrode"], ["power", "lab"], "common", 1, "o", "red",
     "Usually found in power plants.  It looks just like a Poké Ball, and has fooled more than one scavenger."),
    (101, "electrode", "Electrode", ["electric"], (60, 50, 70, 80, 140), 66.6, [], ["power"], "uncommon", 2, "O", "red",
     "It stores electric energy under very high pressure.  It often explodes with little or no provocation."),
    (102, "exeggcute", "Exeggcute", ["grass", "psychic"], (60, 40, 80, 60, 40), 2.5, ["S:leaf:exeggutor"], ["forest", "safari"], "uncommon", 2, "e", "pink",
     "A cluster of six eggs that communicate telepathically.  If one is lost, the rest quickly gather."),
    (103, "exeggutor", "Exeggutor", ["grass", "psychic"], (95, 95, 85, 125, 55), 120.0, [], ["safari"], "none", 2, "E", "yellow",
     "A walking palm tree Pokémon.  Each of its three heads thinks independently."),
    (104, "cubone", "Cubone", ["ground"], (50, 50, 95, 40, 35), 6.5, ["L28:marowak"], ["cave", "urban"], "uncommon", 2, "c", "brown",
     "A lonely Pokémon that wears the skull of its dead mother.  There are more Cubone than ever."),
    (105, "marowak", "Marowak", ["ground"], (60, 80, 110, 50, 45), 45.0, [], ["cave"], "rare", 2, "M", "brown",
     "It throws the bone it holds like a boomerang.  It has grown hardened and fierce."),
    (106, "hitmonlee", "Hitmonlee", ["fighting"], (50, 120, 53, 35, 87), 49.8, [], ["special"], "none", 2, "H", "brown",
     "A kicking fiend.  Its legs freely contract and stretch to land devastating blows."),
    (107, "hitmonchan", "Hitmonchan", ["fighting"], (50, 105, 79, 35, 76), 50.2, [], ["special"], "none", 2, "H", "light_red",
     "Its punches are faster than a bullet train.  It takes a break every three minutes."),
    (108, "lickitung", "Lickitung", ["normal"], (90, 55, 75, 60, 30), 65.5, [], ["field", "swamp"], "rare", 2, "L", "pink",
     "Its tongue is twice its body length.  Its lick leaves a tingling numbness."),
    (109, "koffing", "Koffing", ["poison"], (40, 65, 95, 60, 35), 1.0, ["L35:weezing"], ["urban", "sewer"], "common", 1, "k", "magenta",
     "A floating balloon of toxic gas.  It is attracted to the smell of burning garbage."),
    (110, "weezing", "Weezing", ["poison"], (65, 90, 120, 85, 60), 9.5, [], ["urban"], "uncommon", 2, "W", "magenta",
     "Two Koffing fused together.  It feeds on the poison gases rising from decaying matter."),
    (111, "rhyhorn", "Rhyhorn", ["ground", "rock"], (80, 85, 95, 30, 25), 115.0, ["L42:rhydon"], ["safari", "mountain"], "uncommon", 2, "r", "light_gray",
     "Its massive bones are a thousand times harder than human bones.  It charges blindly and can smash through a semi trailer."),
    (112, "rhydon", "Rhydon", ["ground", "rock"], (105, 130, 120, 45, 40), 120.0, [], ["mountain"], "rare", 2, "R", "light_gray",
     "Protected by armor-like hide, it can live in molten lava.  It walks upright now."),
    (113, "chansey", "Chansey", ["normal"], (250, 5, 5, 105, 50), 34.6, [], ["safari"], "rare", 3, "C", "pink",
     "A kindly Pokémon that shares its nutritious eggs with injured people and Pokémon.  Hospitals once worked alongside them."),
    (114, "tangela", "Tangela", ["grass"], (65, 55, 115, 100, 60), 35.0, [], ["forest", "swamp"], "uncommon", 2, "T", "blue",
     "Its whole body is swathed in wide vines.  The vines sway as it walks."),
    (115, "kangaskhan", "Kangaskhan", ["normal"], (105, 95, 80, 40, 90), 80.0, [], ["safari"], "rare", 3, "K", "brown",
     "The infant in its pouch rarely leaves.  The mother defends it with ferocious strength."),
    (116, "horsea", "Horsea", ["water"], (30, 40, 70, 70, 60), 8.0, ["L32:seadra"], ["ocean"], "common", 1, "h", "light_blue",
     "A seahorse Pokémon that shoots ink to escape predators."),
    (117, "seadra", "Seadra", ["water"], (55, 65, 95, 95, 85), 25.0, [], ["ocean"], "uncommon", 2, "S", "light_blue",
     "Its fins are poisonous.  It spins and generates whirlpools to drown prey."),
    (118, "goldeen", "Goldeen", ["water"], (45, 67, 60, 50, 63), 15.0, ["L33:seaking"], ["water"], "common", 1, "g", "white",
     "A goldfish Pokémon whose tail fin flows elegantly.  It is called the Water Queen."),
    (119, "seaking", "Seaking", ["water"], (80, 92, 65, 80, 68), 39.0, [], ["water"], "uncommon", 2, "S", "light_red",
     "In autumn it swims upstream to lay eggs, using its horn to carve nests in riverbed stones."),
    (120, "staryu", "Staryu", ["water"], (30, 45, 55, 70, 85), 34.5, ["S:water:starmie"], ["ocean"], "common", 1, "s", "brown",
     "A star-shaped Pokémon with a red core that glows at night.  It regenerates lost limbs."),
    (121, "starmie", "Starmie", ["water", "psychic"], (60, 75, 85, 100, 115), 80.0, [], ["ocean"], "none", 2, "S", "magenta",
     "Its central core glows with seven colors.  Some think it is a signal sent into space."),
    (122, "mr_mime", "Mr. Mime", ["psychic"], (40, 45, 65, 100, 90), 54.5, [], ["urban"], "rare", 2, "M", "pink",
     "A master of pantomime.  It solidifies air into invisible walls with its fingertips."),
    (123, "scyther", "Scyther", ["bug", "flying"], (70, 110, 80, 55, 105), 56.0, [], ["safari", "forest"], "rare", 3, "S", "green",
     "With ninja-like agility and scythe-sharp forearms, it cuts down shamblers as easily as tall grass."),
    (124, "jynx", "Jynx", ["ice", "psychic"], (65, 50, 35, 95, 95), 40.6, [], ["special"], "none", 2, "J", "red",
     "It wiggles its hips as it walks.  It can make people dance in unison with it."),
    (125, "electabuzz", "Electabuzz", ["electric"], (65, 83, 57, 85, 105), 30.0, [], ["power"], "rare", 3, "E", "yellow",
     "It loves to feed on strong electricity.  It is said to have caused the last blackouts in Kanto, before the big one."),
    (126, "magmar", "Magmar", ["fire"], (65, 95, 57, 85, 93), 44.5, [], ["mountain"], "rare", 3, "M", "red",
     "Born in an active volcano.  Its body is always burning with an orange glow."),
    (127, "pinsir", "Pinsir", ["bug"], (65, 125, 100, 55, 85), 55.0, [], ["safari", "forest"], "rare", 3, "P", "brown",
     "It grips prey with its pincers and squeezes until they break in two."),
    (128, "tauros", "Tauros", ["normal"], (75, 100, 95, 70, 110), 88.4, [], ["safari", "field"], "uncommon", 3, "T", "brown",
     "A wild bull Pokémon that whips itself with its three tails to charge into battle.  Herds of them now roam the empty farmland."),
    (129, "magikarp", "Magikarp", ["water"], (20, 10, 55, 20, 80), 10.0, ["L20:gyarados"], ["water", "ocean", "swamp"], "common", 1, "m", "red",
     "Famous for being weak and useless.  It can only splash about.  It somehow survived the end of the world anyway."),
    (130, "gyarados", "Gyarados", ["water", "flying"], (95, 125, 79, 100, 81), 235.0, [], ["water", "ocean"], "rare", 2, "G", "blue",
     "Once it begins to rampage, it won't stop until it has destroyed everything nearby.  Avoid the lakes where it lives."),
    (131, "lapras", "Lapras", ["water", "ice"], (130, 85, 80, 95, 60), 220.0, [], ["ocean"], "rare", 4, "L", "light_blue",
     "A gentle, intelligent Pokémon that ferries people across the sea.  It was hunted nearly to extinction."),
    (132, "ditto", "Ditto", ["normal"], (48, 48, 48, 48, 48), 4.0, [], ["urban", "lab"], "uncommon", 2, "d", "magenta",
     "A gooey blob that can rearrange its cell structure to transform into anything it sees.  Some scavengers swear they have seen one imitate a zombie."),
    (133, "eevee", "Eevee", ["normal"], (55, 55, 50, 65, 55), 6.5, ["S:water:vaporeon", "S:thunder:jolteon", "S:fire:flareon"], ["urban", "lab"], "rare", 3, "e", "brown",
     "Its unstable genetic makeup lets it evolve in many different ways when exposed to the radiation of evolution stones."),
    (134, "vaporeon", "Vaporeon", ["water"], (130, 65, 60, 110, 65), 29.0, [], ["special"], "none", 3, "V", "light_blue",
     "Its cells are so similar to water molecules that it melts away when it enters water."),
    (135, "jolteon", "Jolteon", ["electric"], (65, 65, 60, 110, 130), 24.5, [], ["special"], "none", 3, "J", "yellow",
     "It accumulates negative ions in the air and fires off thousand-volt bolts.  Its fur bristles like needles."),
    (136, "flareon", "Flareon", ["fire"], (65, 130, 60, 110, 65), 25.0, [], ["special"], "none", 3, "F", "light_red",
     "It stores heat in a flame sac in its body.  Its temperature can top sixteen hundred degrees."),
    (137, "porygon", "Porygon", ["normal"], (65, 60, 70, 75, 40), 36.5, [], ["lab"], "rare", 3, "P", "light_red",
     "The world's first artificially created Pokémon.  It can move through cyberspace, though there is not much of that left."),
    (138, "omanyte", "Omanyte", ["rock", "water"], (35, 40, 100, 90, 35), 7.5, ["L40:omastar"], ["special"], "none", 3, "o", "light_blue",
     "An ancient Pokémon revived from a fossil.  It swims by twisting its ten tentacles."),
    (139, "omastar", "Omastar", ["rock", "water"], (70, 60, 125, 115, 55), 35.0, [], ["special"], "none", 3, "O", "light_blue",
     "A prehistoric Pokémon that went extinct when its heavy shell made it too slow to catch prey."),
    (140, "kabuto", "Kabuto", ["rock", "water"], (30, 80, 90, 45, 55), 11.5, ["L40:kabutops"], ["special"], "none", 3, "k", "brown",
     "A Pokémon revived from a fossil.  It hides on the sea floor, its eyes glinting beneath its shell."),
    (141, "kabutops", "Kabutops", ["rock", "water"], (60, 115, 105, 70, 80), 40.5, [], ["special"], "none", 3, "K", "brown",
     "Its sleek shape is perfect for swimming.  It slashes prey with its claws and drains their fluids."),
    (142, "aerodactyl", "Aerodactyl", ["rock", "flying"], (80, 105, 65, 60, 130), 59.0, [], ["special"], "none", 3, "A", "light_gray",
     "A ferocious prehistoric Pokémon that goes for the throat with its serrated fangs."),
    (143, "snorlax", "Snorlax", ["normal"], (160, 110, 65, 65, 30), 460.0, [], ["field", "mountain"], "rare", 3, "S", "blue",
     "A colossal Pokémon that does nothing but eat and sleep.  More than one highway has been blocked by a dozing Snorlax since the evacuation."),
    (144, "articuno", "Articuno", ["ice", "flying"], (90, 85, 100, 125, 85), 55.4, [], ["special"], "none", 4, "A", "light_cyan",
     "A legendary bird Pokémon said to appear to doomed travelers lost in icy mountains."),
    (145, "zapdos", "Zapdos", ["electric", "flying"], (90, 90, 85, 125, 100), 52.6, [], ["special"], "none", 4, "Z", "yellow",
     "A legendary bird Pokémon that is said to appear from clouds while dropping enormous lightning bolts."),
    (146, "moltres", "Moltres", ["fire", "flying"], (90, 100, 90, 125, 90), 60.0, [], ["special"], "none", 4, "M", "light_red",
     "A legendary bird Pokémon.  Each flap of its flaming wings is said to herald the coming of spring."),
    (147, "dratini", "Dratini", ["dragon"], (41, 64, 45, 50, 50), 3.3, ["L30:dragonair"], ["water", "safari"], "rare", 3, "d", "light_blue",
     "Long considered a mythical Pokémon until a small colony was found living underwater.  It sheds its skin as it grows."),
    (148, "dragonair", "Dragonair", ["dragon"], (61, 84, 65, 70, 70), 16.5, ["L55:dragonite"], ["water"], "rare", 3, "D", "light_blue",
     "A mystical Pokémon that exudes a gentle aura.  It can change the weather at will."),
    (149, "dragonite", "Dragonite", ["dragon", "flying"], (91, 134, 95, 100, 80), 210.0, [], ["special"], "none", 3, "D", "yellow",
     "An extremely rare Pokémon said to rescue people lost at sea.  It can circle the globe in sixteen hours."),
    (150, "mewtwo", "Mewtwo", ["psychic"], (106, 110, 90, 154, 130), 122.0, [], ["special"], "none", 4, "M", "magenta",
     "A Pokémon created by genetic manipulation in a secret lab.  It survived the Cataclysm in a cave sealed off from the world, and it has no love for humans."),
    (151, "mew", "Mew", ["psychic"], (100, 100, 100, 100, 100), 4.0, [], ["special"], "none", 4, "m", "pink",
     "So rare it is said to be a mirage.  Its DNA is said to contain the genetic codes of all Pokémon.  Sightings have increased since the world ended."),
]

assert len(POKEMON_NUMBERS := [p[0] for p in POKEDEX]) == 151
assert POKEMON_NUMBERS == list(range(1, 152))
